import { db } from '../../../database/db'
import { resolveCountry } from '../../../core/countries'
import { normalizeKey } from '../../imports/core/normalizers'
import { divisionNumber, competitionModule } from '../../rankings/engine/ranking-engine'
import { loadRankingConfig } from '../../rankings/config/ranking-config-store'
import type { Competition, Standing } from '../../../shared/types/entities'

export type RankingDebugSeverity='error'|'warning'|'info'
export interface RankingDebugIssue{id:string;severity:RankingDebugSeverity;code:string;title:string;detail:string;competitionId?:string;standingId?:string;entityId?:string;editable:boolean;suggestedType?:Competition['type'];suggestedLevel?:number}
export interface RankingDebugSnapshot{generatedAt:string;summary:{seasons:number;competitions:number;standings:number;issues:number;errors:number;warnings:number;unknownTypes:number;orphanStandings:number;missingLocations:number;superleagueConflicts:number;duplicates:number};issues:RankingDebugIssue[];competitions:Competition[];clubs:Array<{id:string;name:string;country?:string}>;countryNames:string[]}

function inferredType(competition:Competition):Competition['type']{const module=competitionModule(undefined,competition.name);return module==='superleague'?'super-league':module}
export async function collectRankingDebug():Promise<RankingDebugSnapshot>{
  const [seasons,competitions,standings,clubs,competitionSeasons,importSessions]=await Promise.all([db.seasons.toArray(),db.competitions.toArray(),db.standings.toArray(),db.clubs.toArray(),db.competitionSeasons.toArray(),db.importSessions.toArray()])
  const config=loadRankingConfig(),issues:RankingDebugIssue[]=[]
  const competitionMap=new Map(competitions.map(item=>[item.id,item])),clubMap=new Map(clubs.map(item=>[item.id,item])),seasonIds=new Set(seasons.map(item=>item.id))
  const duplicateCompetitionNames=new Map<string,Competition[]>(),duplicateClubNames=new Map<string,typeof clubs>()
  for(const item of competitions){const list=duplicateCompetitionNames.get(item.normalizedName)??[];list.push(item);duplicateCompetitionNames.set(item.normalizedName,list)}
  for(const item of clubs){const list=duplicateClubNames.get(item.normalizedName)??[];list.push(item);duplicateClubNames.set(item.normalizedName,list)}
  for(const [name,list] of duplicateCompetitionNames)if(list.length>1)issues.push({id:`duplicate-competition:${name}`,severity:'error',code:'DUPLICATE_COMPETITION',title:`Competições duplicadas: ${list[0].name}`,detail:`IDs: ${list.map(item=>item.id).join(', ')}. A duplicação pode dividir pontos e estatísticas.`,competitionId:list[0].id,editable:false})
  for(const [name,list] of duplicateClubNames)if(list.length>1)issues.push({id:`duplicate-club:${name}`,severity:'error',code:'DUPLICATE_CLUB',title:`Clubes duplicados: ${list[0].name}`,detail:`Existem ${list.length} registos com o mesmo nome normalizado.`,entityId:list[0].id,editable:false})
  for(const competition of competitions){
    const suggestedType=inferredType(competition),suggestedLevel=divisionNumber(competition.name)
    if(competition.type==='unknown')issues.push({id:`type:${competition.id}`,severity:'error',code:'COMPETITION_TYPE_UNKNOWN',title:`Tipo desconhecido: ${competition.name}`,detail:`Tipo sugerido pelo nome: ${suggestedType}.`,competitionId:competition.id,editable:true,suggestedType})
    if(competition.type==='super-league'&&!competition.level&&!suggestedLevel)issues.push({id:`level:${competition.id}`,severity:'error',code:'SUPERLEAGUE_LEVEL_MISSING',title:`Divisão em falta: ${competition.name}`,detail:'Sem divisão não é possível aplicar corretamente pesos e subidas.',competitionId:competition.id,editable:true})
    if(competition.type==='super-league'&&!competition.level&&suggestedLevel)issues.push({id:`level-infer:${competition.id}`,severity:'warning',code:'SUPERLEAGUE_LEVEL_INFERRED',title:`Divisão não guardada: ${competition.name}`,detail:`Pode ser corrigida automaticamente para a divisão ${suggestedLevel}.`,competitionId:competition.id,editable:true,suggestedLevel})
    if(!competition.country&&competition.type==='national')issues.push({id:`country:${competition.id}`,severity:'warning',code:'COMPETITION_COUNTRY_MISSING',title:`País em falta: ${competition.name}`,detail:'Os filtros por país e continente ficarão incompletos.',competitionId:competition.id,editable:true})
    if(!competition.continent)issues.push({id:`continent:${competition.id}`,severity:'warning',code:'COMPETITION_CONTINENT_MISSING',title:`Continente em falta: ${competition.name}`,detail:'Os filtros e agregações continentais não conseguem classificar esta competição.',competitionId:competition.id,editable:true})
    if(competition.reputation===undefined)issues.push({id:`reputation:${competition.id}`,severity:'info',code:'COMPETITION_REPUTATION_MISSING',title:`Reputação em falta: ${competition.name}`,detail:'O contexto competitivo dos Scores não poderá utilizar a reputação.',competitionId:competition.id,editable:true})
  }
  for(const standing of standings){
    const competition=competitionMap.get(standing.competitionId)
    if(!competition){issues.push({id:`orphan-competition:${standing.id}`,severity:'error',code:'STANDING_COMPETITION_ORPHAN',title:`Classificação sem competição: ${standing.entityName}`,detail:`competitionId ${standing.competitionId} não existe.`,standingId:standing.id,editable:true});continue}
    if(!seasonIds.has(standing.seasonId))issues.push({id:`orphan-season:${standing.id}`,severity:'error',code:'STANDING_SEASON_ORPHAN',title:`Classificação sem época: ${standing.entityName}`,detail:`seasonId ${standing.seasonId} não existe.`,standingId:standing.id,editable:false})
    if(standing.competitionName!==competition.name)issues.push({id:`competition-name:${standing.id}`,severity:'warning',code:'STANDING_COMPETITION_NAME_CONFLICT',title:`Nome da competição divergente`,detail:`Classificação: ${standing.competitionName}; catálogo: ${competition.name}.`,standingId:standing.id,competitionId:competition.id,editable:true})
    const international=competition.type==='international'
    if(!standing.entityId)issues.push({id:`entity-missing:${standing.id}`,severity:'error',code:'STANDING_ENTITY_MISSING',title:`Entidade não ligada: ${standing.entityName}`,detail:'A classificação não contribuirá corretamente para as entidades.',standingId:standing.id,competitionId:competition.id,editable:true})
    else if(international){const country=resolveCountry(standing.entityName);if(!country.canonical)issues.push({id:`country-standing:${standing.id}`,severity:'error',code:'INTERNATIONAL_COUNTRY_UNKNOWN',title:`Seleção não reconhecida: ${standing.entityName}`,detail:'Normaliza o país no Debug Países e volta a ligar esta classificação.',standingId:standing.id,competitionId:competition.id,editable:true})}
    else if(!clubMap.has(standing.entityId))issues.push({id:`club-standing:${standing.id}`,severity:'error',code:'STANDING_CLUB_ORPHAN',title:`Clube não encontrado: ${standing.entityName}`,detail:`entityId ${standing.entityId} não existe na tabela de clubes.`,standingId:standing.id,competitionId:competition.id,editable:true})
    if(competition.type==='super-league'&&standing.format==='league'){
      const champion=String(standing.info??'').trim().toUpperCase()==='C'
      if(champion&&standing.position!==1)issues.push({id:`champion-conflict:${standing.id}`,severity:'error',code:'SUPERLEAGUE_CHAMPION_CONFLICT',title:`Código C fora do 1.º lugar: ${standing.entityName}`,detail:`Posição ${standing.position??'—'} em ${competition.name}.`,standingId:standing.id,competitionId:competition.id,editable:true})
      if(standing.position===1&&!champion)issues.push({id:`first-not-champion:${standing.id}`,severity:'info',code:'SUPERLEAGUE_FIRST_WITHOUT_C',title:`1.º lugar sem título: ${standing.entityName}`,detail:'Correto pelas regras definidas: recebe pontos da posição, mas não conta como campeão porque Inf não contém C.',standingId:standing.id,competitionId:competition.id,editable:false})
    }
  }
  for(const alias of Object.values(config.competitionAliases))if(!competitions.some(item=>item.normalizedName===normalizeKey(alias)))issues.push({id:`alias-target:${normalizeKey(alias)}`,severity:'warning',code:'RANKING_ALIAS_TARGET_MISSING',title:`Alias aponta para competição inexistente`,detail:`Destino configurado: ${alias}.`,editable:true})
  const completedTypes=new Set(importSessions.filter(item=>item.status==='completed').map(item=>`${item.seasonId}:${item.importType}`));for(const season of seasons){for(const kind of ['competitions','standings'] as const)if(!completedTypes.has(`${season.id}:${kind}`))issues.push({id:`import-missing:${season.id}:${kind}`,severity:'warning',code:'RANKING_IMPORT_MISSING',title:`Importação em falta: ${kind==='standings'?'Classificações':'Competições'} · ${season.label}`,detail:'Os Rankings desta época podem estar incompletos.',editable:false})}
  const countryNames=[...new Set([...clubs.map(item=>item.country),...competitions.map(item=>item.country)].filter((item):item is string=>Boolean(item)))].sort((a,b)=>a.localeCompare(b,'pt-PT'))
  return{generatedAt:new Date().toISOString(),summary:{seasons:seasons.length,competitions:competitions.length,standings:standings.length,issues:issues.length,errors:issues.filter(item=>item.severity==='error').length,warnings:issues.filter(item=>item.severity==='warning').length,unknownTypes:issues.filter(item=>item.code==='COMPETITION_TYPE_UNKNOWN').length,orphanStandings:issues.filter(item=>item.code.includes('ORPHAN')||item.code==='STANDING_ENTITY_MISSING').length,missingLocations:issues.filter(item=>item.code==='COMPETITION_COUNTRY_MISSING'||item.code==='COMPETITION_CONTINENT_MISSING').length,superleagueConflicts:issues.filter(item=>item.code==='SUPERLEAGUE_CHAMPION_CONFLICT').length,duplicates:issues.filter(item=>item.code.startsWith('DUPLICATE_')).length},issues,competitions:competitions.sort((a,b)=>a.name.localeCompare(b.name,'pt-PT')),clubs:clubs.map(item=>({id:item.id,name:item.name,country:item.country})).sort((a,b)=>a.name.localeCompare(b.name,'pt-PT')),countryNames}
}
export async function updateCompetitionDebug(id:string,patch:Partial<Pick<Competition,'name'|'country'|'continent'|'type'|'level'|'reputation'>>):Promise<void>{const row=await db.competitions.get(id);if(!row)return;const name=patch.name?.trim()||row.name;await db.competitions.put({...row,...patch,name,normalizedName:normalizeKey(name)})}
export async function fixStandingCompetitionName(id:string):Promise<void>{const standing=await db.standings.get(id);if(!standing)return;const competition=await db.competitions.get(standing.competitionId);if(competition)await db.standings.put({...standing,competitionName:competition.name})}
export async function relinkStanding(id:string,entityName:string):Promise<void>{const standing=await db.standings.get(id);if(!standing)return;const competition=await db.competitions.get(standing.competitionId);if(competition?.type==='international'){const country=resolveCountry(entityName);const name=country.canonical??entityName.trim();await db.standings.put({...standing,entityName:name,entityId:`country:${normalizeKey(name)}`});return}const club=await db.clubs.where('normalizedName').equals(normalizeKey(entityName)).first();if(club)await db.standings.put({...standing,entityName:club.name,entityId:club.id})}
export async function setStandingChampionCode(id:string,champion:boolean):Promise<void>{const row=await db.standings.get(id);if(row)await db.standings.put({...row,info:champion?'C':undefined})}
export function exportRankingDebug(snapshot:RankingDebugSnapshot):string{return JSON.stringify({version:1,generatedAt:snapshot.generatedAt,summary:snapshot.summary,issues:snapshot.issues},null,2)}
