export type ChallengeSubject='clubs'|'coaches'|'countries'
export type RequirementType='superleague-champion'|'superleague-promotion'|'national-champion'|'continental-winner'|'international-winner'|'hall-of-fame'|'unbeaten-season'|'points-record'
export interface ChallengeRequirement{type:RequirementType;match:string;count:number;consecutive:boolean;hofTopN?:number;leagueScope?:'any'|'superleague'|'national'}
export interface Challenge{id:string;name:string;description:string;subjects:ChallengeSubject[];sameYear:boolean;bonus:number;requirements:ChallengeRequirement[];active:boolean;custom?:boolean;category?:string}
const r=(type:RequirementType,count=1,consecutive=false,extra:Partial<ChallengeRequirement>={}):ChallengeRequirement=>({type,match:'',count,consecutive,...extra})
export const CHALLENGE_PRESETS:Challenge[]=[
{id:'preset-tri-campeao-superleague',name:'Tri-campeão da SuperLeague',description:'Vencer a SuperLeague em 3 épocas consecutivas (clube ou treinador).',subjects:['clubs','coaches'],sameYear:false,bonus:1500,requirements:[r('superleague-champion',3,true)],active:true,category:'Super League'},
{id:'preset-penta-campeao-superleague',name:'Penta-campeão da SuperLeague',description:'5 títulos da SuperLeague (não precisam ser seguidos).',subjects:['clubs','coaches'],sameYear:false,bonus:3000,requirements:[r('superleague-champion',5)],active:true,category:'Super League'},
{id:'preset-dinastia-continental',name:'Dinastia Continental',description:'Vencer uma competição continental 3 anos seguidos.',subjects:['clubs','coaches'],sameYear:false,bonus:2500,requirements:[r('continental-winner',3,true)],active:true,category:'Continental'},
{id:'preset-dobradinha-continental',name:'Dobradinha Continental',description:'Campeão SuperLeague + Vencedor Continental no mesmo ano.',subjects:['clubs','coaches'],sameYear:true,bonus:1200,requirements:[r('superleague-champion'),r('continental-winner')],active:true,category:'Combinado'},
{id:'preset-lenda-hall-of-fame',name:'Lenda do Hall of Fame',description:'Permanecer no Top 10 do Hall of Fame durante 5 anos consecutivos.',subjects:['clubs','coaches'],sameYear:false,bonus:2000,requirements:[r('hall-of-fame',5,true,{hofTopN:10})],active:true,category:'Hall of Fame'},
{id:'preset-elite-hall-of-fame',name:'Elite do Hall of Fame',description:'10 presenças no Top 5 do Hall of Fame.',subjects:['clubs','coaches'],sameYear:false,bonus:2500,requirements:[r('hall-of-fame',10,false,{hofTopN:5})],active:true,category:'Hall of Fame'},
{id:'preset-invencivel-superleague',name:'Invencível na SuperLeague',description:'Concluir uma época da SuperLeague sem derrotas.',subjects:['clubs','coaches'],sameYear:false,bonus:1000,requirements:[r('unbeaten-season',1,false,{leagueScope:'superleague'})],active:true,category:'Super League'},
{id:'preset-invencivel-nacional',name:'Invencível Nacional',description:'Vencer uma liga nacional sem perder.',subjects:['clubs','coaches'],sameYear:false,bonus:800,requirements:[r('unbeaten-season',1,false,{leagueScope:'national'})],active:true,category:'Nacional'},
{id:'preset-recorde-pontos',name:'Recorde de pontos',description:'Bater o recorde de pontos numa liga/divisão.',subjects:['clubs','coaches'],sameYear:false,bonus:600,requirements:[r('points-record')],active:true,category:'Recordes'},
{id:'preset-promocao-express',name:'Promoção Express',description:'Duas promoções ou títulos consecutivos na SuperLeague.',subjects:['clubs','coaches'],sameYear:false,bonus:700,requirements:[r('superleague-promotion',2,true)],active:true,category:'Super League'},
{id:'preset-gloria-internacional',name:'Glória Internacional',description:'Conquistar uma competição internacional de seleções.',subjects:['countries'],sameYear:false,bonus:1500,requirements:[r('international-winner')],active:true,category:'Internacional'},
{id:'preset-bicampeao-internacional',name:'Bicampeão Internacional',description:'Vencer 2 competições internacionais de seleções.',subjects:['countries'],sameYear:false,bonus:2500,requirements:[r('international-winner',2)],active:true,category:'Internacional'},
{id:'preset-imperio-de-um-pais',name:'Império de um país',description:'Seleção + clube do país vencem internacional e continental no mesmo ano.',subjects:['countries'],sameYear:true,bonus:3000,requirements:[r('international-winner'),r('continental-winner')],active:true,category:'Combinado'},
{id:'preset-dominio-nacional',name:'Domínio Nacional',description:'5 títulos de liga nacional.',subjects:['clubs','coaches'],sameYear:false,bonus:1200,requirements:[r('national-champion',5)],active:true,category:'Nacional'},
{id:'preset-colecao-continental',name:'Coleção Continental',description:'Vencer 5 competições continentais.',subjects:['clubs','coaches'],sameYear:false,bonus:4000,requirements:[r('continental-winner',5)],active:true,category:'Continental'},
]
const KEY='fm-data-center-challenges-v2'
export function normalizeChallenge(c:Partial<Challenge>):Challenge{return{id:c.id??`challenge-${crypto.randomUUID()}`,name:c.name?.trim()||'Novo desafio',description:c.description?.trim()||'',subjects:c.subjects?.length?c.subjects:['clubs'],sameYear:!!c.sameYear,bonus:Number(c.bonus)||0,requirements:c.requirements?.length?c.requirements:[r('superleague-champion')],active:c.active!==false,custom:c.custom??true,category:c.category??'Personalizado'}}
export function loadChallenges():Challenge[]{try{const raw=localStorage.getItem(KEY);if(!raw)return CHALLENGE_PRESETS.map(c=>({...c}));const data=JSON.parse(raw) as Partial<Challenge>[];return data.map(normalizeChallenge)}catch{return CHALLENGE_PRESETS.map(c=>({...c}))}}
export function saveChallenges(list:Challenge[]){localStorage.setItem(KEY,JSON.stringify(list));window.dispatchEvent(new Event('fm:challenges-changed'))}
export function loadActiveChallenges(){return loadChallenges().filter(c=>c.active)}
export function resetChallenges(){const list=CHALLENGE_PRESETS.map(c=>({...c}));saveChallenges(list);return list}
export const REQUIREMENT_LABELS:Record<RequirementType,string>={'superleague-champion':'Campeão Super League','superleague-promotion':'Promoção Super League','national-champion':'Campeão nacional','continental-winner':'Vencedor continental','international-winner':'Vencedor internacional','hall-of-fame':'Hall of Fame','unbeaten-season':'Época invicta','points-record':'Recorde de pontos'}
