import { useEffect, useMemo, useState } from 'react'
import { Info, RotateCcw, Save } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { EntityLink } from '../../../shared/components/EntityLink'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import { DEFAULT_STRENGTH_WEIGHTS, loadCompetitionStrength, loadStrengthWeights, saveStrengthWeights, type CompetitionStrengthRow, type StrengthWeights } from '../services/competition-strength-service'
const n=(v?:number)=>v===undefined?'—':v.toLocaleString('pt-PT',{maximumFractionDigits:1}),money=(v?:number)=>v===undefined?'—':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(v)
const labels:Record<keyof StrengthWeights,string>={reputation:'Reputação',currentAbility:'C.A. média',potentialAbility:'C.P. média',marketValue:'Valor de mercado',wages:'Salários',competitiveBalance:'Equilíbrio competitivo',depth:'Profundidade',marketPower:'Poder de mercado',coachQuality:'Qualidade dos treinadores',internationalReach:'Alcance internacional'}
export function CompetitionStrengthPage(){
  const [weights,setWeights]=useState(loadStrengthWeights),[rows,setRows]=useState<CompetitionStrengthRow[]>([]),[seasons,setSeasons]=useState<Array<{id:string;label:string}>>([]),[seasonId,setSeasonId]=useState(''),[type,setType]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<CompetitionStrengthRow|null>(null),[loading,setLoading]=useState(true)
  useEffect(()=>{setLoading(true);void loadCompetitionStrength(seasonId||undefined,weights,true).then(x=>{setRows(x.rows);setSeasons(x.seasons);if(!seasonId)setSeasonId(x.seasons[0]?.id??'');setSelected(s=>x.rows.find(r=>r.id===s?.id)??x.rows[0]??null);setLoading(false)})},[seasonId,weights])
  const filtered=useMemo(()=>rows.filter(r=>(!type||r.type===type)&&(!query||`${r.name} ${r.country} ${r.continent}`.toLowerCase().includes(query.toLowerCase()))),[rows,type,query])
  const columns:ScoreTableColumn<CompetitionStrengthRow>[]=[{key:'rank',label:'#',value:(_,i)=>i+1},{key:'name',label:'Competição',value:r=>r.name,render:r=><button className="entity-link entity-link--button" onClick={()=>setSelected(r)}><EntityLink kind="competition" id={r.id} name={r.name}/></button>},{key:'score',label:'Índice',value:r=>r.score,render:r=><span className={`score-pill ${r.score>=75?'score-elite':r.score>=60?'score-good':r.score>=45?'score-average':'score-low'}`}>{n(r.score)}</span>},{key:'tier',label:'Nível',value:r=>r.tier},{key:'type',label:'Tipo',value:r=>r.type},{key:'country',label:'País',value:r=>r.country,render:r=>r.country?<EntityLink kind="country" name={r.country}/>: '—'},{key:'clubs',label:'Clubes',value:r=>r.clubs},{key:'players',label:'Jogadores',value:r=>r.players},{key:'rep',label:'Reputação',value:r=>r.reputation},{key:'ca',label:'C.A. média',value:r=>r.averageCA},{key:'pa',label:'C.P. média',value:r=>r.averagePA},{key:'value',label:'Valor médio',value:r=>r.averageMarketValue,render:r=>money(r.averageMarketValue)},{key:'wage',label:'Salário médio',value:r=>r.averageWage,render:r=>money(r.averageWage)},{key:'balance',label:'Equilíbrio',value:r=>r.balance},{key:'market',label:'Poder mercado',value:r=>r.marketPower,render:r=>money(r.marketPower)},{key:'coverage',label:'Cobertura',value:r=>r.coverage,render:r=>`${n(r.coverage)}%`}]
  const save=()=>saveStrengthWeights(weights),reset=()=>setWeights({...DEFAULT_STRENGTH_WEIGHTS})
  return <div className="page-stack"><Panel title="Índice de Força das Competições" description="Classificação multidimensional da qualidade competitiva. Todos os componentes, pesos e dados utilizados são explicáveis."><div className="intelligence-toolbar"><select value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}><option value="">Todos os tipos</option><option value="super-league">Super League</option><option value="national">Ligas nacionais</option><option value="continental">Continentais</option><option value="international">Internacionais</option></select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar competição, país ou continente…"/></div></Panel>
  {loading?<Panel title="A calcular o índice"><div className="empty-state"><strong>A normalizar qualidade, mercado e equilíbrio…</strong></div></Panel>:<><div className="stats-grid"><StatCard label="Competições" value={filtered.length}/><StatCard label="Índice médio" value={n(filtered.reduce((s,r)=>s+r.score,0)/(filtered.length||1))}/><StatCard label="Elite / Topo" value={filtered.filter(r=>r.score>=72).length}/><StatCard label="Cobertura média" value={`${n(filtered.reduce((s,r)=>s+r.coverage,0)/(filtered.length||1))}%`}/></div>
  <Panel title="Configuração do índice" description="Os pesos somam livremente; o motor normaliza-os automaticamente."><details className="filters-panel"><summary>Editar pesos do modelo</summary><div className="strength-weight-grid">{(Object.keys(weights) as Array<keyof StrengthWeights>).map(k=><label key={k}>{labels[k]}<input type="number" min="0" value={weights[k]} onChange={e=>setWeights(w=>({...w,[k]:Number(e.target.value)}))}/></label>)}</div><div className="weight-row-actions"><button className="primary-button" onClick={save}><Save size={16}/>Guardar</button><button className="secondary-button" onClick={reset}><RotateCcw size={16}/>Repor</button></div></details></Panel>
  <Panel title="Ranking competitivo" description="Clica numa competição para ver a decomposição do índice."><ReorderableScoreTable tableKey="competition-strength" columns={columns} rows={filtered} rowKey={r=>r.id}/></Panel>
  {selected&&<Panel title={`${selected.name} · ${selected.score}`} description={selected.summary}><div className="strength-detail"><div className="score-formula"><strong>{selected.score}</strong><span>{selected.tier}<br/>Cobertura dos componentes: {n(selected.coverage)}%</span></div><div className="dimension-bars">{Object.entries(selected.components).sort((a,b)=>b[1].contribution-a[1].contribution).map(([k,c])=><div key={k} title={`Valor bruto: ${n(c.raw)} · Peso: ${c.weight} · Contributo: ${n(c.contribution)}`}><span>{labels[k as keyof StrengthWeights]}</span><i><b style={{width:`${c.normalized}%`}}/></i><strong>{n(c.normalized)}</strong></div>)}</div><p className="score-method-note"><Info size={16}/> O índice usa percentis relativos às competições da época selecionada. Um valor alto representa força relativa dentro da base importada.</p></div></Panel>}</>}</div>
}
