import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, TrendingDown, TrendingUp } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { EntityLink } from '../../../shared/components/EntityLink'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import { ProfileLineChart } from '../../profiles/components/ProfileCharts'
import { loadDevelopmentData, type DevelopmentRow } from '../services/development-service'
const n=(v?:number,d=1)=>v===undefined?'—':v.toLocaleString('pt-PT',{maximumFractionDigits:d})
const money=(v?:number)=>v===undefined?'—':new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(v)
export function DevelopmentForecastPage(){
  const [rows,setRows]=useState<DevelopmentRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[minConfidence,setMinConfidence]=useState(0),[selected,setSelected]=useState<DevelopmentRow|null>(null)
  useEffect(()=>{void loadDevelopmentData().then(x=>{setRows(x.rows);setSelected(x.rows[0]??null);setLoading(false)}).catch(e=>{setError(String(e));setLoading(false)})},[])
  const filtered=useMemo(()=>rows.filter(r=>(!query||`${r.name} ${r.club} ${r.position} ${r.nationality}`.toLowerCase().includes(query.toLowerCase()))&&(!status||r.status===status)&&r.confidence>=minConfidence),[rows,query,status,minConfidence])
  const columns:ScoreTableColumn<DevelopmentRow>[]=[{key:'name',label:'Jogador',value:r=>r.name,render:r=><button className="entity-link entity-link--button" onClick={()=>setSelected(r)}><EntityLink kind="player" id={r.id} name={r.name}/></button>},{key:'club',label:'Clube',value:r=>r.club,render:r=>r.club?<EntityLink kind="club" name={r.club}/>: '—'},{key:'age',label:'Idade',value:r=>r.age},{key:'position',label:'Posição',value:r=>r.position},{key:'status',label:'Tendência',value:r=>r.statusLabel,render:r=><span className={`development-status is-${r.status}`}>{r.statusLabel}</span>},{key:'ca',label:'C.A.',value:r=>r.ca},{key:'pa',label:'C.P.',value:r=>r.pa},{key:'gap',label:'Margem',value:r=>r.potentialGap},{key:'trend',label:'Δ C.A./época',value:r=>r.caTrend,render:r=><span className={r.caTrend>0?'market-positive':r.caTrend<0?'market-negative':''}>{r.caTrend>0?'+':''}{n(r.caTrend)}</span>},{key:'projection',label:'Projeção C.A.',value:r=>r.projectionCA},{key:'improve',label:'Prob. melhorar',value:r=>r.improveProbability,render:r=>`${n(r.improveProbability)}%`},{key:'decline',label:'Prob. regredir',value:r=>r.declineProbability,render:r=>`${n(r.declineProbability)}%`},{key:'confidence',label:'Confiança',value:r=>r.confidence,render:r=>`${n(r.confidence)}%`}]
  const rising=rows.filter(r=>r.improveProbability>=60).length,declining=rows.filter(r=>r.declineProbability>=55).length,underused=rows.filter(r=>r.status==='subutilizado').length
  const series=(id:string,label:string,unit:'number'|'money'|'rating',getter:(r:DevelopmentRow['history'][number])=>number|undefined)=>selected?{id,label,unit,description:'Evolução histórica reconhecida.',points:selected.history.map(h=>({seasonId:h.seasonId,season:h.season,value:getter(h)}))}:null
  return <div className="page-stack"><Panel title="Previsão de Desenvolvimento" description="Modelo explicável baseado na evolução de C.A., atributos, utilização, idade e margem potencial. As probabilidades são tendências, não certezas."><div className="intelligence-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar jogador, clube ou posição…"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas as tendências</option>{[...new Map(rows.map(r=>[r.status,r.statusLabel]))].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><label>Confiança mínima<input type="number" min="0" max="100" value={minConfidence} onChange={e=>setMinConfidence(Number(e.target.value))}/></label></div></Panel>
  {error&&<div className="import-message status-error">{error}</div>}{loading?<Panel title="A analisar trajetórias"><div className="empty-state"><strong>A construir séries históricas…</strong></div></Panel>:<><div className="stats-grid"><StatCard label="Jogadores analisados" value={rows.length.toLocaleString('pt-PT')} detail={`${filtered.length} visíveis`}/><StatCard label="Em crescimento" value={rising} detail="Probabilidade de melhoria ≥ 60%"/><StatCard label="Potencial subutilizado" value={underused} detail="Margem elevada e poucos minutos"/><StatCard label="Risco de regressão" value={declining} detail="Probabilidade de queda ≥ 55%"/></div><Panel title="Mapa de desenvolvimento" description="Clica num jogador para abrir a análise detalhada."><ReorderableScoreTable tableKey="development-forecast" columns={columns} rows={filtered} rowKey={r=>r.id} maxRows={1000}/></Panel>
  {selected&&<><Panel title={`${selected.name} · ${selected.statusLabel}`} description={selected.summary}><div className="development-detail"><div className="development-probabilities"><article><TrendingUp/><span>Melhorar</span><strong>{n(selected.improveProbability)}%</strong><i><b style={{width:`${selected.improveProbability}%`}}/></i></article><article><span>Estável</span><strong>{n(selected.stableProbability)}%</strong><i><b style={{width:`${selected.stableProbability}%`}}/></i></article><article><TrendingDown/><span>Regredir</span><strong>{n(selected.declineProbability)}%</strong><i><b style={{width:`${selected.declineProbability}%`}}/></i></article></div><div className="profile-facts"><div><span>C.A. atual</span><strong>{n(selected.ca)}</strong></div><div><span>C.P.</span><strong>{n(selected.pa)}</strong></div><div><span>Projeção próxima época</span><strong>{n(selected.projectionCA)}</strong></div><div><span>Margem potencial</span><strong>{n(selected.potentialGap)}</strong></div><div><span>Tendência atributos</span><strong>{selected.attributeTrend>0?'+':''}{n(selected.attributeTrend,2)}</strong></div><div><span>Confiança</span><strong>{n(selected.confidence)}%</strong></div></div></div>{selected.confidence<50&&<p className="score-method-note"><AlertTriangle size={16}/> Avaliação provisória: poucas épocas ou minutos disponíveis.</p>}</Panel>
  <div className="profile-chart-grid">{[series('ca','Capacidade atual','rating',h=>h.ca),series('attributes','Média de atributos','rating',h=>h.attributeAverage),series('minutes','Minutos','number',h=>h.minutes),series('value','Valor de mercado','money',h=>h.marketValue)].filter((x):x is NonNullable<typeof x>=>Boolean(x)).map(s=><Panel key={s.id} title={s.label} description={s.description}><ProfileLineChart series={s}/></Panel>)}</div></>}</>}</div>
}
