import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, RefreshCw, Users } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { EntityLink } from '../../../shared/components/EntityLink'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import { analyzeTactic, loadTacticalOptions, TACTICAL_FORMATIONS, type TacticalAnalysis, type TacticalAssignment } from '../services/tactical-lab-service'

const n=(v?:number)=>v===undefined?'—':v.toLocaleString('pt-PT',{maximumFractionDigits:1})
export function TacticalLabPage(){
  const [seasons,setSeasons]=useState<Array<{id:string;label:string}>>([]),[clubs,setClubs]=useState<Array<{id:string;name:string}>>([])
  const [seasonId,setSeasonId]=useState(''),[clubId,setClubId]=useState(''),[formationId,setFormationId]=useState(TACTICAL_FORMATIONS[0].id)
  const [analysis,setAnalysis]=useState<TacticalAnalysis|null>(null),[comparison,setComparison]=useState<TacticalAnalysis[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{void loadTacticalOptions().then(x=>{setSeasons(x.seasons);setClubs(x.clubs);setSeasonId(x.seasons[0]?.id??'');setClubId(x.clubs[0]?.id??'')}).catch(e=>setError(String(e)))},[])
  useEffect(()=>{if(!seasonId)return;void loadTacticalOptions(seasonId).then(x=>{setClubs(x.clubs);setClubId(c=>x.clubs.some(v=>v.id===c)?c:x.clubs[0]?.id??'')})},[seasonId])
  useEffect(()=>{if(!seasonId||!clubId)return;let active=true;setLoading(true);setError('');void analyzeTactic(seasonId,clubId,formationId).then(x=>{if(active){setAnalysis(x);setLoading(false)}}).catch(e=>{if(active){setError(e instanceof Error?e.message:String(e));setLoading(false)}});return()=>{active=false}},[seasonId,clubId,formationId])
  const compare=async()=>{if(!seasonId||!clubId)return;setLoading(true);const rows=await Promise.all(TACTICAL_FORMATIONS.map(f=>analyzeTactic(seasonId,clubId,f.id)));setComparison(rows.sort((a,b)=>b.teamScore-a.teamScore));setLoading(false)}
  const columns:ScoreTableColumn<TacticalAssignment>[]=[{key:'slot',label:'Posição',value:r=>r.slot.label},{key:'player',label:'Jogador',value:r=>r.playerName,render:r=>r.playerName?<EntityLink kind="player" id={r.playerId} name={r.playerName}/>:<span className="status-error">Sem opção</span>},{key:'natural',label:'Posição natural',value:r=>r.position},{key:'role',label:'Role recomendada',value:r=>r.roleName},{key:'score',label:'Adequação',value:r=>r.adjustedScore,render:r=><span className={`score-pill ${(r.adjustedScore??0)>=75?'score-elite':(r.adjustedScore??0)>=60?'score-good':(r.adjustedScore??0)>=45?'score-average':'score-low'}`}>{n(r.adjustedScore)}</span>},{key:'confidence',label:'Confiança',value:r=>r.confidence,render:r=>`${n(r.confidence)}%`},{key:'coverage',label:'Cobertura',value:r=>r.coverage,render:r=>`${n(r.coverage)}%`},{key:'alternatives',label:'Alternativas',value:r=>r.alternatives.map(x=>x.playerName).join(', '),render:r=>r.alternatives.length?r.alternatives.map(x=>`${x.playerName} (${n(x.score)})`).join(' · '):'—'}]
  const byLine=useMemo(()=>analysis?(['GK','DEF','MID','AM','ATT'] as const).map(line=>({line,rows:analysis.assignments.filter(a=>a.slot.line===line)})).filter(x=>x.rows.length):[],[analysis])
  return <div className="page-stack">
    <Panel title="Laboratório Tático" description="Constrói o melhor onze por formação usando Scores de role, atributos, desempenho, contexto e confiança da amostra."><div className="intelligence-toolbar"><label>Época<select value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Clube<select value={clubId} onChange={e=>setClubId(e.target.value)}>{clubs.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Formação<select value={formationId} onChange={e=>setFormationId(e.target.value)}>{TACTICAL_FORMATIONS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button className="secondary-button" onClick={compare}><RefreshCw size={16}/>Comparar formações</button></div></Panel>
    {error&&<div className="import-message status-error">{error}</div>}{loading&&<Panel title="A analisar o plantel"><div className="empty-state"><strong>A calcular adequações e equilíbrio…</strong></div></Panel>}
    {!loading&&analysis&&<><div className="stats-grid"><StatCard label="Adequação do onze" value={n(analysis.teamScore)} detail="Score ajustado médio"/><StatCard label="Profundidade" value={n(analysis.depthScore)} detail="Qualidade das segundas opções"/><StatCard label="Confiança" value={`${n(analysis.confidence)}%`} detail="Minutos e tamanho da amostra"/><StatCard label="Cobertura" value={`${n(analysis.coverage)}%`} detail="Atributos e métricas reconhecidos"/></div>
    <div className="tactical-layout"><Panel title={`${analysis.formation.name} · ${analysis.clubName}`} description={analysis.formation.description}><div className="tactical-board">{byLine.map(group=><div className={`tactical-line tactical-line--${group.line.toLowerCase()}`} key={group.line}>{group.rows.map(a=><article key={a.slot.id} className={!a.playerId?'is-empty':''}><small>{a.slot.label}</small><strong>{a.playerName??'Sem jogador'}</strong><span>{a.roleName??'Sem role compatível'}</span><b>{n(a.adjustedScore)}</b></article>)}</div>)}</div></Panel><div className="page-stack"><Panel title="Leitura do modelo" description="Conclusões automáticas e limitações."><div className="tactical-findings"><section><h3><CheckCircle2/>Pontos fortes</h3>{analysis.strengths.map(x=><p key={x}>{x}</p>)}{!analysis.strengths.length&&<p>Sem vantagem estrutural forte reconhecida.</p>}</section><section><h3><AlertTriangle/>Riscos</h3>{analysis.risks.map(x=><p key={x}>{x}</p>)}{!analysis.risks.length&&<p>Não foram identificados riscos críticos.</p>}</section></div></Panel><Panel title="Identidade disponível" description="Dimensões inferidas a partir dos jogadores do clube."><div className="dimension-bars">{Object.entries(analysis.style).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=><div key={k}><span>{k.replace(/-/g,' ')}</span><i><b style={{width:`${v}%`}}/></i><strong>{n(v)}</strong></div>)}</div></Panel></div></div>
    <Panel title="Onze e funções" description="Todas as colunas podem ser ordenadas e reorganizadas."><ReorderableScoreTable tableKey="tactical-xi" columns={columns} rows={analysis.assignments} rowKey={r=>r.slot.id}/></Panel>
    {!!comparison.length&&<Panel title="Comparação de formações" description="Ordenação pela adequação média do melhor onze, profundidade e cobertura."><div className="formation-comparison">{comparison.map((x,i)=><article key={x.formation.id} className={x.formation.id===formationId?'is-active':''}><span>#{i+1}</span><div><strong>{x.formation.name}</strong><small>{x.formation.description}</small></div><b>{n(x.teamScore)}</b><small>Prof. {n(x.depthScore)} · Cob. {n(x.coverage)}%</small></article>)}</div></Panel>}
    <Panel title="Jogadores fora do onze" description="Melhor adequação encontrada entre as roles relevantes da formação."><div className="compact-card-grid">{analysis.unusedPlayers.slice(0,18).map(p=><article key={p.id}><Users size={17}/><EntityLink kind="player" id={p.id} name={p.name}/><span>{p.position??'Posição desconhecida'}</span><strong>{n(p.bestScore)}</strong></article>)}</div></Panel></>}
  </div>
}
