import { useEffect, useMemo, useState } from 'react'
import { Plus, X } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { EntityLink } from '../../../shared/components/EntityLink'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import type { ProfileKind, ProfileOption } from '../../profiles/types'
import { compareEntities, loadComparatorOptions, type CompareBundle, type CompareMetric } from '../services/comparator-service'
import { ComparisonLineChart } from '../components/ComparisonChart'
const labels:Record<ProfileKind,string>={competition:'Competições',club:'Clubes',player:'Jogadores',coach:'Treinadores'}
const format=(v:number|undefined,unit:CompareMetric['unit'])=>v===undefined?'—':unit==='money'?new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',notation:'compact',maximumFractionDigits:1}).format(v):unit==='percent'?`${v.toLocaleString('pt-PT',{maximumFractionDigits:1})}%`:v.toLocaleString('pt-PT',{maximumFractionDigits:1})
export function UniversalComparatorPage(){
  const [kind,setKind]=useState<ProfileKind>('player'),[options,setOptions]=useState<ProfileOption[]>([]),[query,setQuery]=useState(''),[selectedIds,setSelectedIds]=useState<string[]>([]),[bundle,setBundle]=useState<CompareBundle|null>(null),[loading,setLoading]=useState(false),[evolutionId,setEvolutionId]=useState('')
  useEffect(()=>{setOptions([]);setSelectedIds([]);setBundle(null);void loadComparatorOptions(kind).then(setOptions)},[kind])
  useEffect(()=>{if(!selectedIds.length){setBundle(null);return}setLoading(true);void compareEntities(kind,selectedIds).then(x=>{setBundle(x);setEvolutionId(id=>x.evolution.some(e=>e.id===id)?id:x.evolution[0]?.id??'');setLoading(false)})},[kind,selectedIds])
  const suggestions=useMemo(()=>{const k=query.toLowerCase();return options.filter(o=>!selectedIds.includes(o.id)&&(!k||`${o.name} ${o.subtitle}`.toLowerCase().includes(k))).slice(0,12)},[options,selectedIds,query])
  const add=(id:string)=>setSelectedIds(ids=>ids.length>=5?ids:ids.includes(id)?ids:[...ids,id]),remove=(id:string)=>setSelectedIds(ids=>ids.filter(x=>x!==id))
  const columns:ScoreTableColumn<CompareMetric>[]=[{key:'metric',label:'Métrica',value:r=>r.label,render:r=><span title={r.description}>{r.label}</span>},...(bundle?.profiles??[]).map(p=>({key:p.id,label:p.name,value:(r:CompareMetric)=>r.values[p.id],render:(r:CompareMetric)=>format(r.values[p.id],r.unit)}))]
  const evolution=bundle?.evolution.find(e=>e.id===evolutionId)
  return <div className="page-stack"><Panel title="Comparador Universal" description="Compara até cinco entidades do mesmo tipo através de mercado, evolução, estilo, qualidade e conquistas."><div className="comparator-toolbar"><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value as ProfileKind)}>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="comparator-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Adicionar ${labels[kind].toLowerCase()}…`}/>{query&&<div className="comparator-suggestions">{suggestions.map(o=><button key={o.id} onClick={()=>{add(o.id);setQuery('')}}><Plus size={15}/><span><strong>{o.name}</strong><small>{o.subtitle}</small></span></button>)}</div>}</div><span>{selectedIds.length}/5 selecionados</span></div><div className="comparison-selected">{selectedIds.map(id=>{const o=options.find(x=>x.id===id);return <span key={id}>{o?.name??id}<button onClick={()=>remove(id)}><X size={14}/></button></span>})}</div></Panel>
  {!selectedIds.length&&<Panel title="Seleciona entidades"><div className="empty-state"><strong>Adiciona entre duas e cinco entidades para iniciar a comparação.</strong></div></Panel>}{loading&&<Panel title="A comparar"><div className="empty-state"><strong>A cruzar perfis, histórico e evolução…</strong></div></Panel>}
  {!loading&&bundle&&<><Panel title="Comparação principal" description="Cabeçalhos reordenáveis e valores normalizados apenas quando indicado."><ReorderableScoreTable tableKey={`universal-comparator:${kind}`} columns={columns} rows={bundle.metrics} rowKey={r=>r.id}/></Panel>
  {!!bundle.styleDimensions.length&&<Panel title="Identidade e estilo" description="Dimensões do estilo de jogo disponíveis nos perfis selecionados."><div className="comparison-style-grid">{bundle.styleDimensions.map(d=><article key={d.id}><strong>{d.label}</strong>{bundle.profiles.map(p=><div key={p.id}><span><EntityLink kind={kind} id={p.id} name={p.name}/></span><i><b style={{width:`${d.values[p.id]??0}%`}}/></i><small>{format(d.values[p.id],'rating')}</small></div>)}</article>)}</div></Panel>}
  {!!bundle.evolution.length&&<Panel title="Evolução comparada" description="Seleciona uma série histórica comum às entidades."><select value={evolutionId} onChange={e=>setEvolutionId(e.target.value)}>{bundle.evolution.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select>{evolution&&<ComparisonLineChart series={evolution.series}/>}</Panel>}
  <Panel title="Destaques automáticos" description="Lideranças objetivas nas métricas com dados disponíveis."><div className="score-insight-grid">{bundle.highlights.map((h,i)=><article key={h}><span>{i+1}</span><p>{h}</p></article>)}</div></Panel></>}</div>
}
