import { useEffect, useMemo, useState } from 'react'
import { Flag, Search } from 'lucide-react'
import { db } from '../../../database/db'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { EntityLink } from '../../../shared/components/EntityLink'
import { normalizeCountryInput } from '../../../core/countries/country-normalization'
import { useAppNavigation } from '../../../app/AppNavigationContext'

interface CountryData { name:string; continent?:string; clubs:Array<{id:string;name:string;reputation?:number}>; competitions:Array<{id:string;name:string;type:string;reputation?:number}>; players:Array<{id:string;name:string}>; coaches:Array<{id:string;name:string}> }
const canon=(value?:string)=>value?normalizeCountryInput(value).canonicalName??value:undefined
export function CountryProfilePage(){
  const { target } = useAppNavigation()
  const [countries,setCountries]=useState<string[]>([]),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[data,setData]=useState<CountryData|null>(null),[loading,setLoading]=useState(true)
  useEffect(()=>{void Promise.all([db.clubs.toArray(),db.competitions.toArray(),db.players.toArray(),db.coaches.toArray()]).then(([clubs,competitions,players,coaches])=>{const names=new Set<string>();for(const value of [...clubs.map(x=>x.country),...competitions.map(x=>x.country),...players.map(x=>x.nationality),...coaches.map(x=>x.nationality)]){const name=canon(value);if(name)names.add(name)}const list=[...names].sort((a,b)=>a.localeCompare(b,'pt-PT'));setCountries(list);setSelected(x=>{const requested=target?.kind==='country'?canon(target.name):undefined;return requested&&list.includes(requested)?requested:x&&list.includes(x)?x:list[0]??''});setLoading(false)})},[target?.nonce])
  useEffect(()=>{if(target?.kind!=='country')return;const requested=canon(target.name);if(requested&&countries.includes(requested))setSelected(requested)},[target?.nonce,countries])
  useEffect(()=>{if(!selected){setData(null);return}setLoading(true);void Promise.all([db.clubs.toArray(),db.competitions.toArray(),db.players.toArray(),db.coaches.toArray()]).then(([clubs,competitions,players,coaches])=>{const relatedClubs=clubs.filter(x=>canon(x.country)===selected),relatedCompetitions=competitions.filter(x=>canon(x.country)===selected),relatedPlayers=players.filter(x=>canon(x.nationality)===selected),relatedCoaches=coaches.filter(x=>canon(x.nationality)===selected);setData({name:selected,continent:relatedClubs.find(x=>x.continent)?.continent??relatedCompetitions.find(x=>x.continent)?.continent,clubs:relatedClubs,competitions:relatedCompetitions,players:relatedPlayers,coaches:relatedCoaches});setLoading(false)})},[selected])
  const visible=useMemo(()=>{const key=query.toLowerCase();return countries.filter(x=>!key||x.toLowerCase().includes(key)).slice(0,250)},[countries,query])
  return <div className="page-stack profile-page"><Panel title="Selecionar país" description="Perfil agregado de clubes, competições, jogadores e treinadores."><div className="profile-selector"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar país…"/></label><select value={selected} onChange={e=>setSelected(e.target.value)}>{visible.map(x=><option key={x}>{x}</option>)}</select><span>{visible.length} resultados</span></div></Panel>{loading?<Panel title="A construir perfil" description="A cruzar entidades nacionais."><div className="empty-state"><strong>A analisar…</strong></div></Panel>:data&&<><section className="profile-hero"><div className="profile-hero__mark"><Flag/></div><div><span>País</span><h2>{data.name}</h2><p>{data.continent??'Continente não identificado'}</p></div></section><div className="stats-grid"><StatCard label="Clubes" value={data.clubs.length}/><StatCard label="Competições" value={data.competitions.length}/><StatCard label="Jogadores" value={data.players.length}/><StatCard label="Treinadores" value={data.coaches.length}/></div><div className="profile-two-columns"><Panel title="Clubes" description="Clubes associados ao país."><div className="entity-list">{data.clubs.slice(0,100).map(x=><div key={x.id}><EntityLink kind="club" id={x.id} name={x.name}/><span>Reputação {x.reputation??'—'}</span></div>)}</div></Panel><Panel title="Competições" description="Competições nacionais ou sediadas no país."><div className="entity-list">{data.competitions.slice(0,100).map(x=><div key={x.id}><EntityLink kind="competition" id={x.id} name={x.name}/><span>{x.type} · reputação {x.reputation??'—'}</span></div>)}</div></Panel></div><div className="profile-two-columns"><Panel title="Jogadores" description="Jogadores da nacionalidade."><div className="entity-list">{data.players.slice(0,100).map(x=><div key={x.id}><EntityLink kind="player" id={x.id} name={x.name}/></div>)}</div></Panel><Panel title="Treinadores" description="Treinadores da nacionalidade."><div className="entity-list">{data.coaches.slice(0,100).map(x=><div key={x.id}><EntityLink kind="coach" id={x.id} name={x.name}/></div>)}</div></Panel></div></>}</div>
}
