import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, RefreshCw, UserRoundPlus, Wrench } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { listCountryCatalog, COUNTRY_OVERRIDES_EVENT } from '../../../core/countries'
import { applyContinentFix, applyCountryAliasFix, assignCoachToNationalTeam, collectCountryDebug, normalizeCountryAcrossDatabase, setEntityCountry, unlinkNationalCoach, type CountryDebugIssue, type CountryDebugSnapshot } from '../services/country-debug-service'
import { IMPORT_COMPLETED_EVENT } from '../../imports/services/import-events'

const labels = { error: 'Erro', warning: 'Aviso', info: 'Informação' } as const
const continents = ['Europa', 'África', 'Ásia', 'América do Norte', 'América do Sul', 'Oceânia', 'Antártida']

export function DebugCountriesPage() {
  const [snapshot, setSnapshot] = useState<CountryDebugSnapshot | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [query, setQuery] = useState('')
  const [severity, setSeverity] = useState('all')
  const [tab, setTab] = useState<'issues' | 'teams' | 'map'>('issues')
  const [canonical, setCanonical] = useState<Record<string, string>>({})
  const [continent, setContinent] = useState<Record<string, string>>({})
  const [entityCountry, setEntityCountryValue] = useState<Record<string, string>>({})
  const [assigning, setAssigning] = useState<CountryDebugIssue | null>(null)
  const [coachId, setCoachId] = useState('')
  const [coachRole, setCoachRole] = useState('Selecionador')
  const [teamCountry, setTeamCountry] = useState('')
  const catalog = useMemo(() => listCountryCatalog(), [])
  const refresh = useCallback(async () => { setLoading(true); try { setSnapshot(await collectCountryDebug()); setError(null) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Erro no Debug Países') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh(); const listener = () => void refresh(); window.addEventListener(COUNTRY_OVERRIDES_EVENT, listener); window.addEventListener(IMPORT_COMPLETED_EVENT, listener); return () => { window.removeEventListener(COUNTRY_OVERRIDES_EVENT, listener); window.removeEventListener(IMPORT_COMPLETED_EVENT, listener) } }, [refresh])
  const filtered = useMemo(() => snapshot?.issues.filter((item) => { if (severity !== 'all' && item.severity !== severity) return false; return !query || `${item.title} ${item.detail} ${item.raw ?? ''}`.toLowerCase().includes(query.toLowerCase()) }) ?? [], [snapshot, query, severity])
  const filteredTeams = useMemo(() => snapshot?.nationalTeams.filter((item) => !query || `${item.country} ${item.seasonLabel} ${item.competitions.join(' ')} ${item.coaches.map((row) => row.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())) ?? [], [snapshot, query])
  const applyAlias = async (issue: CountryDebugIssue) => { if (!issue.raw) return; const value = canonical[issue.id]?.trim(); if (!value) return; await applyCountryAliasFix(issue.raw, value, continent[issue.id]); await refresh() }
  const saveEntity = async (issue: CountryDebugIssue) => { if (!issue.entityType || !issue.entityId) return; const country = entityCountry[issue.id]?.trim(); if (!country) return; await setEntityCountry({ entityType: issue.entityType, entityId: issue.entityId, country, continent: continent[issue.id] }); await refresh() }
  const assignCoach = async () => {
    const country = assigning?.raw || teamCountry.trim()
    if (!country || !assigning?.seasonId || !coachId) return
    await assignCoachToNationalTeam({ coachId, seasonId: assigning.seasonId, country, role: coachRole })
    setAssigning(null); setCoachId(''); setTeamCountry(''); await refresh()
  }

  return <div className="page-stack">
    <Panel title="Debug Países" description="Normalização global de países, nacionalidades, continentes e seleções nacionais para Clubes, Competições, Jogadores, Treinadores, Rankings e Scores.">
      <div className="diagnostic-toolbar"><button className="primary-button" onClick={() => void refresh()}><RefreshCw size={15} /> Atualizar diagnóstico</button><button className="secondary-button" onClick={async () => { await normalizeCountryAcrossDatabase(); await refresh() }}><Wrench size={15} /> Normalizar toda a base</button></div>
      {error && <div className="import-message status-error">{error}</div>}
      <div className="debug-summary-grid"><article><span>Nomes distintos</span><strong>{snapshot?.summary.countries ?? '—'}</strong></article><article><span>Resolvidos automaticamente</span><strong>{snapshot?.summary.resolved ?? '—'}</strong></article><article><span>Overrides manuais</span><strong>{snapshot?.summary.overrides ?? '—'}</strong></article><article className="is-error"><span>Desconhecidos</span><strong>{snapshot?.summary.unknown ?? '—'}</strong></article><article className="is-error"><span>Ambíguos</span><strong>{snapshot?.summary.ambiguous ?? '—'}</strong></article><article className="is-warning"><span>Entidades sem país</span><strong>{snapshot?.summary.missingCountries ?? '—'}</strong></article><article className="is-warning"><span>Conflitos de continente</span><strong>{snapshot?.summary.continentConflicts ?? '—'}</strong></article><article><span>Seleções analisadas</span><strong>{snapshot?.summary.nationalTeams ?? '—'}</strong></article><article className="is-warning"><span>Seleções sem treinador</span><strong>{snapshot?.summary.nationalTeamsWithoutCoach ?? '—'}</strong></article><article className="is-error"><span>Seleções com vários treinadores</span><strong>{snapshot?.summary.nationalTeamsMultipleCoaches ?? '—'}</strong></article><article><span>Catálogo canónico</span><strong>{catalog.length}</strong></article></div>
      <div className="score-method-note"><strong>Como funciona</strong><p>O motor ignora maiúsculas/minúsculas, acentos e pontuação; reconhece português, inglês, ISO-2, ISO-3, abreviaturas futebolísticas e aliases. As seleções são identificadas pelas classificações internacionais e cruzadas com os treinadores por época.</p></div>
    </Panel>

    <Panel title="Explorar países e seleções" description="Resolve aliases, conflitos de continente, entidades sem país e seleções sem selecionador.">
      <div className="ranking-tabs ranking-tabs--secondary"><button className={tab === 'issues' ? 'is-active' : ''} onClick={() => setTab('issues')}>Problemas</button><button className={tab === 'teams' ? 'is-active' : ''} onClick={() => setTab('teams')}>Seleções nacionais</button><button className={tab === 'map' ? 'is-active' : ''} onClick={() => setTab('map')}>Mapa de normalização</button></div>
      <div className="filter-grid"><input placeholder="Pesquisar país, seleção, treinador ou problema" value={query} onChange={(event) => setQuery(event.target.value)} />{tab === 'issues' && <select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">Todas as severidades</option><option value="error">Erros</option><option value="warning">Avisos</option><option value="info">Informação</option></select>}</div>
      {tab === 'issues' && <div className="debug-issue-list">{loading ? <p>A analisar países…</p> : filtered.map((issue) => <article key={issue.id} className={`debug-issue debug-issue--${issue.severity}`}><div className="debug-issue__icon">{issue.severity === 'error' ? <AlertTriangle /> : <CheckCircle2 />}</div><div className="debug-issue__body"><div className="debug-issue__title"><strong>{issue.title}</strong><span>{labels[issue.severity]} · {issue.code}</span></div><p>{issue.detail}</p>
        {(issue.code === 'COUNTRY_UNKNOWN' || issue.code === 'COUNTRY_AMBIGUOUS') && issue.raw && <div className="debug-fix-row"><input list="country-catalog" placeholder="País canónico" value={canonical[issue.id] ?? ''} onChange={(event) => setCanonical((current) => ({ ...current, [issue.id]: event.target.value }))} /><select value={continent[issue.id] ?? ''} onChange={(event) => setContinent((current) => ({ ...current, [issue.id]: event.target.value }))}><option value="">Continente automático</option>{continents.map((item) => <option key={item}>{item}</option>)}</select><button className="primary-button" onClick={() => void applyAlias(issue)}>Criar alias e normalizar</button></div>}
        {issue.code === 'CONTINENT_CONFLICT' && issue.raw && <div className="debug-fix-row"><select value={continent[issue.id] ?? issue.expectedContinent ?? ''} onChange={(event) => setContinent((current) => ({ ...current, [issue.id]: event.target.value }))}>{continents.map((item) => <option key={item}>{item}</option>)}</select><button className="primary-button" onClick={async () => { await applyContinentFix(issue.raw!, continent[issue.id] ?? issue.expectedContinent ?? ''); await refresh() }}>Aplicar continente</button></div>}
        {issue.code === 'COUNTRY_MISSING' && issue.entityType && issue.entityId && <div className="debug-fix-row"><input list="country-catalog" placeholder="País da entidade" value={entityCountry[issue.id] ?? ''} onChange={(event) => setEntityCountryValue((current) => ({ ...current, [issue.id]: event.target.value }))} /><select value={continent[issue.id] ?? ''} onChange={(event) => setContinent((current) => ({ ...current, [issue.id]: event.target.value }))}><option value="">Continente automático</option>{continents.map((item) => <option key={item}>{item}</option>)}</select><button className="primary-button" onClick={() => void saveEntity(issue)}>Guardar país</button></div>}
        {issue.code === 'NATIONAL_TEAM_WITHOUT_COACH' && <div className="debug-fix-row"><button className="primary-button" onClick={() => setAssigning(issue)}><UserRoundPlus size={14} /> Associar selecionador</button></div>}
        {issue.code === 'INTERNATIONAL_TEAM_NOT_IDENTIFIED' && issue.entityId && <div className="debug-fix-row"><button className="primary-button" onClick={() => { setAssigning(issue); setCoachId(issue.entityId ?? ''); setTeamCountry('') }}><UserRoundPlus size={14} /> Indicar seleção manualmente</button></div>}
        {issue.code === 'NATIONAL_TEAM_MULTIPLE_COACHES' && issue.relatedIds?.map((id) => <div className="debug-fix-row" key={id}><button className="danger-button" onClick={async () => { await unlinkNationalCoach(id); await refresh() }}>Remover ligação {snapshot?.nationalTeams.flatMap((row) => row.coaches).find((row) => row.coachSeasonId === id)?.name ?? ''}</button></div>)}
      </div></article>)}{!loading && !filtered.length && <div className="debug-empty"><CheckCircle2 size={28} /><strong>Sem problemas para estes filtros</strong></div>}</div>}
      {tab === 'teams' && <div className="table-scroll"><table className="preview-table"><thead><tr><th>Seleção</th><th>Época</th><th>Competições internacionais</th><th>Selecionador(es)</th><th>Problemas</th><th>Ação</th></tr></thead><tbody>{filteredTeams.map((item) => <tr key={item.id}><td><strong>{item.country}</strong></td><td>{item.seasonLabel}</td><td>{item.competitions.join(', ')}</td><td>{item.coaches.map((row) => `${row.name}${row.role ? ` (${row.role})` : ''}`).join(', ') || '—'}</td><td className={item.issueCount ? 'status-error' : 'status-ok'}>{item.issueCount}</td><td>{!item.coaches.length ? <button className="primary-button" onClick={() => setAssigning({ id: item.id, severity: 'warning', code: 'NATIONAL_TEAM_WITHOUT_COACH', title: `${item.country} sem treinador`, detail: '', raw: item.country, seasonId: item.seasonId, editable: true })}>Associar</button> : item.coaches.map((row) => <button key={row.coachSeasonId} className="danger-button" onClick={async () => { await unlinkNationalCoach(row.coachSeasonId); await refresh() }}>Remover {row.name}</button>)}</td></tr>)}</tbody></table></div>}
      {tab === 'map' && <div className="table-scroll"><table className="preview-table"><thead><tr><th>Nome encontrado</th><th>Estado</th><th>Nome canónico</th><th>Inglês</th><th>ISO-2</th><th>ISO-3</th><th>Continente</th><th>Ocorrências</th><th>Origem</th></tr></thead><tbody>{snapshot?.usages.filter((item) => !query || `${item.raw} ${item.resolution.canonical ?? ''} ${item.resolution.english ?? ''}`.toLowerCase().includes(query.toLowerCase())).map((item) => <tr key={item.normalized}><td><strong>{item.raw}</strong></td><td className={item.resolution.status === 'unknown' || item.resolution.status === 'ambiguous' ? 'status-error' : 'status-ok'}>{item.resolution.status}</td><td>{item.resolution.canonical ?? '—'}</td><td>{item.resolution.english ?? '—'}</td><td>{item.resolution.alpha2 ?? '—'}</td><td>{item.resolution.alpha3 ?? '—'}</td><td>{item.resolution.continent ?? '—'}</td><td>{item.count}</td><td>{item.sources.join(', ')}</td></tr>)}</tbody></table></div>}
      <datalist id="country-catalog">{catalog.map((item) => <option key={item.alpha3} value={item.canonical}>{item.english} · {item.alpha3}</option>)}</datalist>
    </Panel>

    {assigning && <div className="modal-backdrop" onClick={() => setAssigning(null)}><div className="editor-modal debug-editor-modal--compact" onClick={(event) => event.stopPropagation()}><div className="ranking-explain__header"><div><span className="eyebrow">Selecionador nacional</span><h2>{assigning.raw || 'Selecionar equipa nacional'}</h2></div><button className="secondary-button" onClick={() => setAssigning(null)}>Fechar</button></div><div className="form-grid">{!assigning.raw && <label className="span-2">Seleção<input list="country-catalog" placeholder="País da seleção" value={teamCountry} onChange={(event) => setTeamCountry(event.target.value)} /></label>}<label className="span-2">Treinador<select value={coachId} onChange={(event) => setCoachId(event.target.value)}><option value="">Selecionar treinador</option>{snapshot?.coaches.map((item) => <option key={item.id} value={item.id}>{item.name}{item.nationality ? ` · ${item.nationality}` : ''}</option>)}</select></label><label className="span-2">Função<input value={coachRole} onChange={(event) => setCoachRole(event.target.value)} /></label></div><p className="muted-copy">Se o treinador já tiver outro clube ou seleção nesta época, a ligação será substituída.</p><button className="primary-button" disabled={!coachId || (!assigning.raw && !teamCountry.trim())} onClick={() => void assignCoach()}>Associar selecionador</button></div></div>}
  </div>
}
