import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Download, RefreshCw, Wrench } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { collectRankingDebug, exportRankingDebug, fixStandingCompetitionName, relinkStanding, setStandingChampionCode, updateCompetitionDebug, type RankingDebugIssue, type RankingDebugSnapshot } from '../services/ranking-debug-service'
import { IMPORT_COMPLETED_EVENT } from '../../imports/services/import-events'
import type { Competition } from '../../../shared/types/entities'

function downloadJson(name:string,content:string){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
const labels={error:'Erro',warning:'Aviso',info:'Informação'} as const

export function DebugRankingsPage(){
  const [snapshot,setSnapshot]=useState<RankingDebugSnapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[query,setQuery]=useState(''),[severity,setSeverity]=useState('all'),[code,setCode]=useState('all')
  const [editing,setEditing]=useState<Competition|null>(null),[entityNames,setEntityNames]=useState<Record<string,string>>({})
  const refresh=useCallback(async()=>{setLoading(true);try{setSnapshot(await collectRankingDebug());setError(null)}catch(caught){setError(caught instanceof Error?caught.message:'Erro no Debug Rankings')}finally{setLoading(false)}},[])
  useEffect(()=>{void refresh();const listener=()=>void refresh();window.addEventListener(IMPORT_COMPLETED_EVENT,listener);window.addEventListener('fm-ranking-config-changed',listener);return()=>{window.removeEventListener(IMPORT_COMPLETED_EVENT,listener);window.removeEventListener('fm-ranking-config-changed',listener)}},[refresh])
  const codes=useMemo(()=>[...new Set(snapshot?.issues.map(item=>item.code)??[])].sort(),[snapshot])
  const filtered=useMemo(()=>snapshot?.issues.filter(item=>{if(severity!=='all'&&item.severity!==severity)return false;if(code!=='all'&&item.code!==code)return false;return!query||`${item.title} ${item.detail} ${item.code}`.toLowerCase().includes(query.toLowerCase())})??[],[snapshot,query,severity,code])
  const competitionFor=(issue:RankingDebugIssue)=>snapshot?.competitions.find(item=>item.id===issue.competitionId)
  const fix=async(action:()=>Promise<void>)=>{await action();await refresh()}
  const saveCompetition=async()=>{if(!editing)return;await updateCompetitionDebug(editing.id,{name:editing.name,country:editing.country,continent:editing.continent,type:editing.type,level:editing.level,reputation:editing.reputation});setEditing(null);await refresh()}
  return <div className="page-stack">
    <Panel title="Debug Rankings" description="Auditoria de competições, classificações, entidades, épocas, regras da Super League, pesos e ligações usadas nos Rankings.">
      <div className="diagnostic-toolbar"><button className="primary-button" onClick={()=>void refresh()}><RefreshCw size={15}/> Atualizar diagnóstico</button><button className="secondary-button" disabled={!snapshot} onClick={()=>snapshot&&downloadJson(`debug-rankings-${new Date().toISOString().slice(0,10)}.json`,exportRankingDebug(snapshot))}><Download size={15}/> Exportar diagnóstico</button></div>
      {error&&<div className="import-message status-error">{error}</div>}
      <div className="debug-summary-grid"><article><span>Épocas</span><strong>{snapshot?.summary.seasons??'—'}</strong></article><article><span>Competições</span><strong>{snapshot?.summary.competitions??'—'}</strong></article><article><span>Classificações</span><strong>{snapshot?.summary.standings.toLocaleString('pt-PT')??'—'}</strong></article><article className="is-error"><span>Erros</span><strong>{snapshot?.summary.errors??'—'}</strong></article><article className="is-warning"><span>Avisos</span><strong>{snapshot?.summary.warnings??'—'}</strong></article><article><span>Tipos desconhecidos</span><strong>{snapshot?.summary.unknownTypes??'—'}</strong></article><article><span>Classificações órfãs</span><strong>{snapshot?.summary.orphanStandings??'—'}</strong></article><article><span>Conflitos Super League</span><strong>{snapshot?.summary.superleagueConflicts??'—'}</strong></article></div>
    </Panel>
    <Panel title="Erros, conflitos e correções" description="As correções alteram diretamente a base local. Usa a reimportação apenas quando o problema estiver no ficheiro de origem.">
      <div className="filter-grid"><input placeholder="Pesquisar competição, entidade ou código" value={query} onChange={event=>setQuery(event.target.value)}/><select value={severity} onChange={event=>setSeverity(event.target.value)}><option value="all">Todas as severidades</option><option value="error">Erros</option><option value="warning">Avisos</option><option value="info">Informação</option></select><select value={code} onChange={event=>setCode(event.target.value)}><option value="all">Todos os tipos</option>{codes.map(item=><option key={item}>{item}</option>)}</select></div>
      <div className="debug-issue-list">{loading?<p>A auditar Rankings…</p>:filtered.map(issue=>{const competition=competitionFor(issue);return <article key={issue.id} className={`debug-issue debug-issue--${issue.severity}`}><div className="debug-issue__icon">{issue.severity==='error'?<AlertTriangle/>:<CheckCircle2/>}</div><div className="debug-issue__body"><div className="debug-issue__title"><strong>{issue.title}</strong><span>{labels[issue.severity]} · {issue.code}</span></div><p>{issue.detail}</p><div className="debug-fix-row">
        {competition&&issue.editable&&<button className="secondary-button" onClick={()=>setEditing({...competition})}><Wrench size={14}/> Editar competição</button>}
        {issue.code==='COMPETITION_TYPE_UNKNOWN'&&issue.competitionId&&issue.suggestedType&&<button className="primary-button" onClick={()=>void fix(()=>updateCompetitionDebug(issue.competitionId!,{type:issue.suggestedType}))}>Aplicar tipo {issue.suggestedType}</button>}
        {issue.code==='SUPERLEAGUE_LEVEL_INFERRED'&&issue.competitionId&&issue.suggestedLevel&&<button className="primary-button" onClick={()=>void fix(()=>updateCompetitionDebug(issue.competitionId!,{level:issue.suggestedLevel}))}>Guardar divisão {issue.suggestedLevel}</button>}
        {issue.code==='STANDING_COMPETITION_NAME_CONFLICT'&&issue.standingId&&<button className="primary-button" onClick={()=>void fix(()=>fixStandingCompetitionName(issue.standingId!))}>Usar nome do catálogo</button>}
        {(issue.code==='STANDING_ENTITY_MISSING'||issue.code==='STANDING_CLUB_ORPHAN'||issue.code==='INTERNATIONAL_COUNTRY_UNKNOWN')&&issue.standingId&&<><input list={`entities-${issue.id}`} placeholder="Nome correto do clube/país" value={entityNames[issue.id]??''} onChange={event=>setEntityNames(current=>({...current,[issue.id]:event.target.value}))}/><datalist id={`entities-${issue.id}`}>{snapshot?.clubs.map(item=><option key={item.id} value={item.name}/>)}</datalist><button className="primary-button" onClick={()=>void fix(()=>relinkStanding(issue.standingId!,entityNames[issue.id]??''))}>Ligar entidade</button></>}
        {issue.code==='SUPERLEAGUE_CHAMPION_CONFLICT'&&issue.standingId&&<button className="secondary-button" onClick={()=>void fix(()=>setStandingChampionCode(issue.standingId!,false))}>Remover código C</button>}
      </div></div></article>})}{!loading&&!filtered.length&&<div className="debug-empty"><CheckCircle2 size={28}/><strong>Sem problemas para estes filtros</strong></div>}</div>
    </Panel>
    <Panel title="Catálogo de competições" description="Revisão rápida dos campos que condicionam pesos, filtros, subidas, contexto competitivo e agregações."><div className="table-scroll"><table className="preview-table"><thead><tr><th>Competição</th><th>Tipo</th><th>Divisão</th><th>País</th><th>Continente</th><th>Reputação</th><th>Ação</th></tr></thead><tbody>{snapshot?.competitions.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td className={item.type==='unknown'?'status-error':''}>{item.type}</td><td>{item.level??'—'}</td><td>{item.country??'—'}</td><td>{item.continent??'—'}</td><td>{item.reputation??'—'}</td><td><button className="secondary-button" onClick={()=>setEditing({...item})}>Editar</button></td></tr>)}</tbody></table></div></Panel>
    {editing&&<div className="modal-backdrop" onClick={()=>setEditing(null)}><div className="editor-modal" onClick={event=>event.stopPropagation()}><div className="ranking-explain__header"><div><span className="eyebrow">Correção manual</span><h2>{editing.name}</h2></div><button className="secondary-button" onClick={()=>setEditing(null)}>Fechar</button></div><div className="form-grid"><label>Nome<input value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})}/></label><label>Tipo<select value={editing.type} onChange={event=>setEditing({...editing,type:event.target.value as Competition['type']})}><option value="unknown">Desconhecido</option><option value="national">Nacional</option><option value="continental">Continental</option><option value="international">Internacional</option><option value="super-league">Super League</option></select></label><label>Divisão<input type="number" value={editing.level??''} onChange={event=>setEditing({...editing,level:event.target.value?Number(event.target.value):undefined})}/></label><label>Reputação<input type="number" value={editing.reputation??''} onChange={event=>setEditing({...editing,reputation:event.target.value?Number(event.target.value):undefined})}/></label><label>País<input value={editing.country??''} onChange={event=>setEditing({...editing,country:event.target.value||undefined})}/></label><label>Continente<input value={editing.continent??''} onChange={event=>setEditing({...editing,continent:event.target.value||undefined})}/></label></div><button className="primary-button" onClick={()=>void saveCompetition()}>Guardar correção</button></div></div>}
  </div>
}
