import { useMemo, useState } from 'react'
import type { ScoreConfig, ScoreFeatureKind, ScoreInferenceDimension, ScoreInferenceFeature } from '../config/types'

const slug=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
const newFeature=(kind:ScoreFeatureKind):ScoreInferenceFeature=>({id:kind==='metric'?'nova-metrica':'novo-atributo',kind,weight:10,direction:'higher'})

export function InferenceConfigEditor({config,onChange}:{config:ScoreConfig;onChange:(config:ScoreConfig)=>void}){
  const[dimensionId,setDimensionId]=useState(config.inferenceDimensions[0]?.id??'')
  const[query,setQuery]=useState('')
  const dimension=config.inferenceDimensions.find(item=>item.id===dimensionId)??config.inferenceDimensions[0]
  const dimensions=useMemo(()=>config.inferenceDimensions.filter(item=>!query||item.name.toLowerCase().includes(query.toLowerCase())),[config.inferenceDimensions,query])
  const updateDimension=(patch:Partial<ScoreInferenceDimension>)=>{if(!dimension)return;onChange({...config,inferenceDimensions:config.inferenceDimensions.map(item=>item.id===dimension.id?{...item,...patch}:item)})}
  const addDimension=()=>{const name=`Nova dimensão ${config.inferenceDimensions.length+1}`;const next:ScoreInferenceDimension={id:`${slug(name)}-${Date.now()}`,name,description:'Nova dimensão inferida a partir dos dados configurados.',features:[]};onChange({...config,inferenceDimensions:[...config.inferenceDimensions,next]});setDimensionId(next.id)}
  const duplicateDimension=()=>{if(!dimension)return;const next={...JSON.parse(JSON.stringify(dimension)) as ScoreInferenceDimension,id:`${dimension.id}-copia-${Date.now()}`,name:`${dimension.name} — Cópia`};onChange({...config,inferenceDimensions:[...config.inferenceDimensions,next]});setDimensionId(next.id)}
  const deleteDimension=()=>{if(!dimension||config.inferenceDimensions.length===1||!confirm(`Apagar a dimensão “${dimension.name}”?`))return;const next=config.inferenceDimensions.filter(item=>item.id!==dimension.id);onChange({...config,inferenceDimensions:next});setDimensionId(next[0]?.id??'')}
  const updateFeature=(index:number,patch:Partial<ScoreInferenceFeature>)=>{if(!dimension)return;updateDimension({features:dimension.features.map((item,itemIndex)=>itemIndex===index?{...item,...patch}:item)})}
  const removeFeature=(index:number)=>{if(!dimension)return;updateDimension({features:dimension.features.filter((_,itemIndex)=>itemIndex!==index)})}
  const addFeature=(kind:ScoreFeatureKind)=>{if(!dimension)return;updateDimension({features:[...dimension.features,newFeature(kind)]})}
  if(!dimension)return null
  return <div className="score-config-layout score-inference-editor"><aside className="score-role-list"><div className="action-row"><button className="secondary-button" onClick={addDimension}>Nova dimensão</button></div><input className="history-search" placeholder="Procurar dimensão" value={query} onChange={event=>setQuery(event.target.value)}/>{dimensions.map(item=><button key={item.id} className={item.id===dimension.id?'score-role-button is-active':'score-role-button'} onClick={()=>setDimensionId(item.id)}><strong>{item.name}</strong><small>{item.features.length} componentes</small></button>)}</aside><div className="score-config-main"><div className="form-grid"><label>Nome<input value={dimension.name} onChange={event=>updateDimension({name:event.target.value})}/></label><label className="form-grid-wide">Descrição<textarea rows={3} value={dimension.description} onChange={event=>updateDimension({description:event.target.value})}/></label></div><div className="action-row score-role-actions"><button className="secondary-button" onClick={duplicateDimension}>Duplicar dimensão</button><button className="danger-button" onClick={deleteDimension}>Apagar dimensão</button><button className="secondary-button" onClick={()=>addFeature('metric')}>Adicionar métrica</button><button className="secondary-button" onClick={()=>addFeature('attribute')}>Adicionar atributo</button></div><div className="table-scroll"><table className="preview-table"><thead><tr><th>Tipo</th><th>ID canónico</th><th>Peso</th><th>Direção</th><th></th></tr></thead><tbody>{dimension.features.map((feature,index)=><tr key={`${feature.kind}:${index}`}><td><select value={feature.kind} onChange={event=>updateFeature(index,{kind:event.target.value as ScoreFeatureKind})}><option value="metric">Métrica</option><option value="attribute">Atributo</option></select></td><td><input value={feature.id} onChange={event=>updateFeature(index,{id:slug(event.target.value)})}/></td><td><input className="weight-input" type="number" min="0" step=".5" value={feature.weight} onChange={event=>updateFeature(index,{weight:Number(event.target.value)})}/></td><td><select value={feature.direction} onChange={event=>updateFeature(index,{direction:event.target.value as 'higher'|'lower'})}><option value="higher">Mais é melhor</option><option value="lower">Menos é melhor</option></select></td><td><button className="danger-button" onClick={()=>removeFeature(index)}>Retirar</button></td></tr>)}</tbody></table></div><div className="score-method-note"><strong>Total configurado: {dimension.features.reduce((sum,item)=>sum+item.weight,0).toFixed(1)}%</strong><p>As dimensões alimentam os perfis de clubes e competições e os Insights. Os IDs devem corresponder aos nomes canónicos guardados pelo importador.</p></div></div></div>
}
