export type ScoreFeatureKind = 'attribute' | 'metric'
export type ScoreDirection = 'higher' | 'lower'
export type ScoreRoleCategory = 'goalkeeper' | 'outfield'
export type ScoreNormalizationScope = 'global' | 'position' | 'competition' | 'position-competition'
export interface ScoreFeatureWeight { id:string; label:string; weight:number; enabled:boolean; direction:ScoreDirection }
export interface ScoreRoleDefinition { id:string; name:string; category:ScoreRoleCategory; positionGroups:string[]; enabled:boolean; components:{attributes:number;metrics:number;context:number}; attributes:ScoreFeatureWeight[]; metrics:ScoreFeatureWeight[]; notes?:string }
export interface ScoreInferenceFeature { id:string; kind:ScoreFeatureKind; weight:number; direction:ScoreDirection }
export interface ScoreInferenceDimension { id:string; name:string; description:string; features:ScoreInferenceFeature[] }
export interface ScoreConfig { version:number; normalizationScope:ScoreNormalizationScope; minimumMinutes:number; provisionalMinutes:number; contextEnabled:boolean; missingFeatureStrategy:'renormalize'|'zero'; roles:ScoreRoleDefinition[]; inferenceDimensions:ScoreInferenceDimension[] }
export interface ScoreFeatureContribution { id:string; label:string; kind:ScoreFeatureKind; rawValue:number|null; normalizedValue:number|null; weight:number; contribution:number; direction:ScoreDirection; available:boolean }
export interface PlayerRoleScore { playerId:string; playerName:string; seasonId:string; clubId?:string; clubName?:string; competitionId?:string; competitionName?:string; position?:string; age?:number; nationality?:string; roleId:string; roleName:string; score:number; attributeScore:number; performanceScore:number; contextScore:number; confidence:number; coverage:number; adjustedScore:number; minutes:number; appearances:number; strengths:string[]; limitations:string[]; contributions:ScoreFeatureContribution[] }
export interface EntityDimensionContribution { id:string; label:string; kind:ScoreFeatureKind; weight:number; direction:ScoreDirection; averageRawValue?:number; normalizedValue?:number; availablePlayers:number; totalPlayers:number }
export interface EntityStyleProfile { entityId:string; entityName:string; seasonId:string; playerCount:number; dimensions:Record<string,number>; dimensionCoverage:Record<string,number>; dimensionContributions:Record<string,EntityDimensionContribution[]>; missingFeatures:string[]; summary:string; strongestDimension?:string; weakestDimension?:string; averageRoleScore?:number; averages:{marketValue?:number;wageAnnual?:number;currentAbility?:number;potentialAbility?:number;rating?:number} }
export interface ScoreFeatureAvailability { id:string; label:string; kind:ScoreFeatureKind; availableRows:number; totalRows:number; coverage:number; status:'available'|'partial'|'missing' }
export interface ScorePlayerData { playerId:string; playerName:string; seasonId:string; clubId?:string; clubName?:string; competitionId?:string; competitionName?:string; position?:string; age?:number; nationality?:string; appearances:number; minutes:number; attributes:Record<string,number>; metrics:Record<string,number>; context:{competitionReputation?:number;competitionWeight?:number} }
