import { useEffect, useMemo, useState } from 'react'
import { History, RefreshCw } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { EntityLink } from '../../../shared/components/EntityLink'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import type { RankingEntity, RankingMode, RankingModule } from '../../rankings/config/default-ranking-config'
import { loadAnalyticsBundle, num, type AnalyticsBundle } from '../services/analytics-service'
import { buildHistoricalRankings, rankingValue } from '../services/ranking-analytics-service'

interface Row { id:string; name:string; total:number; bestRank:number; averageRank?:number; appearances:number; firstSeason?:string; lastSeason?:string; yearly:Record<string,{points:number;rank:number}> }
const entityLabel:Record<RankingEntity,string>={clubs:'Clubes',coaches:'Treinadores',countries:'Países',players:'Jogadores',competitions:'Competições'}
const entityKind=(entity:RankingEntity)=>entity==='clubs'?'club':entity==='coaches'?'coach':entity==='countries'?'country':entity==='players'?'player':'competition'

export function RankingHistoryPage(){
  const [data,setData]=useState<AnalyticsBundle|null>(null),[loading,setLoading]=useState(true),[entity,setEntity]=useState<RankingEntity>('clubs'),[module,setModule]=useState<RankingModule>('all'),[mode,setMode]=useState<RankingMode>('weighted'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState(''),[top,setTop]=useState(50)
  const refresh=()=>{setLoading(true);void loadAnalyticsBundle(true).then(value=>{setData(value);setLoading(false)})}
  useEffect(()=>{void loadAnalyticsBundle().then(value=>{setData(value);setLoading(false)})},[])
  const historical=useMemo(()=>data?buildHistoricalRankings(data,entity,module,mode):[],[data,entity,module,mode])
  const selectedSeasons=useMemo(()=>{if(!data)return[];const fromYear=from?data.seasons.find(x=>x.id===from)?.startYear:-Infinity,toYear=to?data.seasons.find(x=>x.id===to)?.endYear:Infinity;return historical.filter(x=>x.startYear>=fromYear!&&x.endYear<=toYear!)},[data,historical,from,to])
  const rows=useMemo<Row[]>(()=>{const map=new Map<string,Row>();for(const season of selectedSeasons){for(const entry of season.entries){const id=entry.entityId??`${entity}:${entry.name}`;const current=map.get(id)??{id,name:entry.name,total:0,bestRank:Number.POSITIVE_INFINITY,appearances:0,yearly:{}};current.total+=rankingValue(entry,mode);current.bestRank=Math.min(current.bestRank,entry.rank);current.appearances++;current.firstSeason=current.firstSeason??season.season;current.lastSeason=season.season;current.yearly[season.seasonId]={points:rankingValue(entry,mode),rank:entry.rank};map.set(id,current)}}for(const row of map.values()){const ranks=Object.values(row.yearly).map(x=>x.rank);row.averageRank=ranks.length?ranks.reduce((a,b)=>a+b,0)/ranks.length:undefined}const key=query.trim().toLowerCase();return[...map.values()].filter(x=>!key||x.name.toLowerCase().includes(key)).sort((a,b)=>b.total-a.total).slice(0,top)},[selectedSeasons,mode,entity,query,top])
  const columns=useMemo<ScoreTableColumn<Row>[]>(()=>[
    {key:'entity',label:entityLabel[entity].slice(0,-1),value:r=>r.name,render:r=><EntityLink kind={entityKind(entity)} id={r.id.startsWith(`${entity}:`)?undefined:r.id} name={r.name}/>},
    {key:'total',label:mode==='weighted'?'Pontos ponderados':'Pontos brutos',value:r=>r.total,render:r=><strong>{num(r.total,1)}</strong>},
    {key:'best',label:'Melhor posição',value:r=>r.bestRank===Number.POSITIVE_INFINITY?9999:r.bestRank,render:r=>r.bestRank===Number.POSITIVE_INFINITY?'—':`${r.bestRank}.º`},
    {key:'average',label:'Posição média',value:r=>r.averageRank??9999,render:r=>r.averageRank?num(r.averageRank,1):'—'},
    {key:'seasons',label:'Épocas pontuadas',value:r=>r.appearances},
    {key:'first',label:'Primeira época',value:r=>r.firstSeason??''},
    {key:'last',label:'Última época',value:r=>r.lastSeason??''},
    ...selectedSeasons.map(season=>({key:`season:${season.seasonId}`,label:season.season,help:'Posição e pontos nessa época.',value:(r:Row)=>r.yearly[season.seasonId]?.rank??9999,render:(r:Row)=>{const item=r.yearly[season.seasonId];return item?<span title={`${num(item.points,1)} pontos`}>{item.rank}.º<small className="score-subline">{num(item.points,1)} pts</small></span>:'—'}})),
  ],[entity,mode,selectedSeasons])
  const leader=rows[0]
  return <div className="page-stack"><Panel title="Evolução dos Rankings" description="Reconstrução do Histórico de Rankings: posição, pontos e trajetória de cada entidade em todas as épocas."><div className="ranking-tabs">{(['clubs','coaches','countries'] as RankingEntity[]).map(x=><button key={x} className={entity===x?'is-active':''} onClick={()=>setEntity(x)}>{entityLabel[x]}</button>)}</div><div className="filter-grid"><select value={module} onChange={e=>setModule(e.target.value as RankingModule)}><option value="all">Unificado</option><option value="superleague">Super Leagues</option><option value="national">Ligas Nacionais</option><option value="continental">Continentais</option><option value="international">Internacionais</option></select><select value={mode} onChange={e=>setMode(e.target.value as RankingMode)}><option value="weighted">Ponderado</option><option value="raw">Bruto</option></select><select value={from} onChange={e=>setFrom(e.target.value)}><option value="">Desde o início</option>{data?.seasons.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><select value={to} onChange={e=>setTo(e.target.value)}><option value="">Até à última</option>{data?.seasons.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar entidade…"/><select value={top} onChange={e=>setTop(Number(e.target.value))}>{[20,50,100,250,1000].map(x=><option key={x} value={x}>Top {x}</option>)}</select><button className="secondary-button" onClick={refresh}><RefreshCw size={15}/> Atualizar</button></div></Panel>{loading?<Panel title="A calcular histórico" description="A reconstruir cada época."><p>A analisar…</p></Panel>:<><div className="stats-grid"><StatCard label="Entidades" value={rows.length}/><StatCard label="Épocas" value={selectedSeasons.length}/><StatCard label="Líder histórico" value={leader?.name??'—'} detail={leader?`${num(leader.total,1)} pontos`:undefined}/><StatCard label="Modo" value={mode==='weighted'?'Ponderado':'Bruto'} detail={module==='all'?'Unificado':module}/></div><Panel title="Matriz histórica" description="Cada coluna anual mostra a posição e os pontos da entidade naquela época. Todas as colunas são ordenáveis e reorganizáveis."><ReorderableScoreTable tableKey={`ranking-history:${entity}:${module}:${mode}`} columns={columns} rows={rows} rowKey={r=>r.id}/></Panel><Panel title="Como interpretar" description="Metodologia do histórico."><div className="profile-style-identity"><History/><div><strong>Uma classificação independente por época</strong><p>A posição anual é recalculada usando apenas a respetiva época. O total histórico soma os pontos anuais dentro do intervalo selecionado, sem aplicar decaimento entre épocas.</p></div></div></Panel></>}</div>
}
