import { useEffect, useMemo, useRef, useState } from 'react'
import { Copy, Download, Lightbulb, RotateCcw, Save, Trash2, Upload } from 'lucide-react'
import { Panel } from '../../../shared/components/Panel'
import { StatCard } from '../../../shared/components/StatCard'
import { ReorderableScoreTable, type ScoreTableColumn } from '../../scores/components/ReorderableScoreTable'
import { EntityLink } from '../../../shared/components/EntityLink'
import { average, loadAnalyticsBundle, metric, money, num, type AnalyticsBundle } from '../services/analytics-service'
import { loadRankingConfig, saveRankingConfig } from '../../rankings/config/ranking-config-store'

const PROFILE_KEY = 'fm-data-center.weight-suggestion-profiles.v1'
type MetricKey = 'goals'|'assists'|'games'|'playerOfMatch'|'ca'|'pa'|'rating'|'marketValue'|'wage'|'age'|'clubReputation'|'competitionReputation'
type Normalization = 'percentile'|'minmax'
interface Formula { name:string; enabled:Record<MetricKey,boolean>; weights:Record<MetricKey,number>; normalization:Normalization; scale:number }
interface FormulaProfile { id:string; name:string; formula:Formula }
interface Suggestion { id:string; name:string; type:string; country?:string; players:number; coverage:number; metrics:Record<MetricKey,number|undefined>; index:number; suggested:number; current:number; difference:number }
const METRICS: Array<{key:MetricKey;label:string;description:string;invert?:boolean}> = [
  {key:'goals',label:'Golos',description:'Produção média de golos dos jogadores da competição.'},
  {key:'assists',label:'Assistências',description:'Produção média de assistências.'},
  {key:'games',label:'Jogos',description:'Participações médias por jogador.'},
  {key:'playerOfMatch',label:'Homem do Jogo',description:'Prémios de melhor em campo por jogador.'},
  {key:'ca',label:'C.A.',description:'Capacidade Atual média.'},
  {key:'pa',label:'C.P.',description:'Capacidade Potencial média.'},
  {key:'rating',label:'Avaliação',description:'Avaliação média dos jogadores.'},
  {key:'marketValue',label:'Valor de mercado',description:'Valor médio dos jogadores.'},
  {key:'wage',label:'Salário',description:'Salário anual médio.'},
  {key:'age',label:'Juventude',description:'Idade média invertida: menor idade aumenta a sugestão.',invert:true},
  {key:'clubReputation',label:'Reputação média dos clubes',description:'Reputação média dos clubes participantes.'},
  {key:'competitionReputation',label:'Reputação da competição',description:'Reputação importada da competição.'},
]
const DEFAULT:Formula={name:'Modelo equilibrado',normalization:'percentile',scale:2.5,enabled:{goals:true,assists:true,games:true,playerOfMatch:true,ca:true,pa:true,rating:true,marketValue:true,wage:true,age:true,clubReputation:true,competitionReputation:true},weights:{goals:6,assists:4,games:3,playerOfMatch:3,ca:24,pa:16,rating:12,marketValue:10,wage:5,age:4,clubReputation:7,competitionReputation:6}}
const clone=<T,>(value:T):T=>JSON.parse(JSON.stringify(value)) as T
const normalizeValue=(value:number|undefined,values:number[],mode:Normalization,invert=false)=>{if(value===undefined||!values.length)return undefined;let normalized=50;if(mode==='percentile')normalized=values.filter(item=>item<=value).length/values.length*100;else{const min=Math.min(...values),max=Math.max(...values);normalized=max>min?(value-min)/(max-min)*100:50}return invert?100-normalized:normalized}
const loadProfiles=():FormulaProfile[]=>{try{return JSON.parse(localStorage.getItem(PROFILE_KEY)??'[]') as FormulaProfile[]}catch{return[]}}
const saveProfiles=(rows:FormulaProfile[])=>localStorage.setItem(PROFILE_KEY,JSON.stringify(rows))

export function WeightSuggestionsPage(){
  const [data,setData]=useState<AnalyticsBundle|null>(null)
  const [formula,setFormula]=useState<Formula>(()=>clone(DEFAULT))
  const [query,setQuery]=useState('')
  const [type,setType]=useState('all')
  const [selected,setSelected]=useState<Set<string>>(new Set())
  const [profiles,setProfiles]=useState<FormulaProfile[]>(loadProfiles)
  const [activeProfile,setActiveProfile]=useState('')
  const fileRef=useRef<HTMLInputElement>(null)
  useEffect(()=>{void loadAnalyticsBundle().then(setData)},[])
  const rawRows=useMemo(()=>{if(!data)return[];const playerSeasons=new Map(data.playerSeasons.map(row=>[`${row.playerId}|${row.seasonId}`,row])),clubs=new Map(data.clubs.map(row=>[row.id,row])),config=loadRankingConfig();return data.competitions.map(comp=>{const stats=data.stats.filter(row=>row.competitionId===comp.id),uniqueProfiles=[...new Map(stats.map(row=>[row.playerId,playerSeasons.get(`${row.playerId}|${row.seasonId}`)])).values()].filter((row):row is NonNullable<typeof row>=>Boolean(row)),participants=[...new Set(stats.map(row=>row.clubId).filter((id):id is string=>Boolean(id)))].map(id=>clubs.get(id)).filter((row):row is NonNullable<typeof row>=>Boolean(row));const values:Record<MetricKey,number|undefined>={goals:average(stats.map(row=>row.goals)),assists:average(stats.map(row=>row.assists)),games:average(stats.map(row=>row.appearances)),playerOfMatch:average(stats.map(row=>metric(row,['playerOfMatch','homemDoJogo','hdj','potm']))),ca:average(stats.map(row=>metric(row,['currentAbility','c_a','ca']))),pa:average(stats.map(row=>metric(row,['potentialAbility','c_p','pa']))),rating:average(stats.map(row=>metric(row,['averageRating','cl_med','avaliacao']))),marketValue:average(uniqueProfiles.map(row=>row.marketValue)),wage:average(uniqueProfiles.map(row=>row.wageAnnual)),age:average(uniqueProfiles.map(row=>row.age)),clubReputation:average(participants.map(row=>row.reputation)),competitionReputation:comp.reputation};const current=config.competitionSpecificWeights.find(item=>comp.name.toLowerCase().includes(item.match.toLowerCase()))?.weight??config.competitionWeights[comp.type==='super-league'?'superleague':comp.type==='continental'?'continental':comp.type==='international'?'international':'national'];return{id:comp.id,name:comp.name,type:comp.type,country:comp.country,players:new Set(stats.map(row=>row.playerId)).size,values,current}})},[data])
  const rows=useMemo<Suggestion[]>(()=>{const distributions={} as Record<MetricKey,number[]>;for(const item of METRICS)distributions[item.key]=rawRows.map(row=>row.values[item.key]).filter((value):value is number=>value!==undefined);const totalWeight=METRICS.reduce((sum,item)=>sum+(formula.enabled[item.key]?Math.max(0,formula.weights[item.key]):0),0)||1;return rawRows.map(row=>{let weighted=0,availableWeight=0,available=0;for(const item of METRICS){if(!formula.enabled[item.key])continue;const weight=Math.max(0,formula.weights[item.key]),normalized=normalizeValue(row.values[item.key],distributions[item.key],formula.normalization,item.invert);if(normalized===undefined)continue;weighted+=normalized*weight;availableWeight+=weight;available++}const index=availableWeight?weighted/availableWeight:0,suggested=Math.max(.05,Number((index/100*formula.scale).toFixed(2))),coverage=METRICS.filter(item=>formula.enabled[item.key]).length?available/METRICS.filter(item=>formula.enabled[item.key]).length*100:0;return{id:row.id,name:row.name,type:row.type,country:row.country,players:row.players,coverage,metrics:row.values,index,suggested,current:row.current,difference:Number((suggested-row.current).toFixed(2))}}).filter(row=>(type==='all'||row.type===type)&&(!query||`${row.name} ${row.country??''}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.suggested-a.suggested)},[rawRows,formula,type,query])
  const columns:ScoreTableColumn<Suggestion>[]=[
    {key:'select',label:'Aplicar',value:row=>selected.has(row.id)?1:0,render:row=><input type="checkbox" checked={selected.has(row.id)} onChange={event=>setSelected(current=>{const next=new Set(current);event.target.checked?next.add(row.id):next.delete(row.id);return next})}/>},
    {key:'name',label:'Competição',value:row=>row.name,render:row=><><EntityLink kind="competition" id={row.id} name={row.name}/><small className="score-subline">{row.country?<EntityLink kind="country" name={row.country}/>:''}</small></>},
    {key:'type',label:'Tipo',value:row=>row.type},{key:'players',label:'Jogadores',value:row=>row.players},{key:'coverage',label:'Cobertura',value:row=>row.coverage,render:row=>`${num(row.coverage,0)}%`},
    {key:'goals',label:'Golos',value:row=>row.metrics.goals,render:row=>num(row.metrics.goals,2)},{key:'assists',label:'Ast',value:row=>row.metrics.assists,render:row=>num(row.metrics.assists,2)},{key:'games',label:'Jogos',value:row=>row.metrics.games,render:row=>num(row.metrics.games,1)},{key:'potm',label:'HdJ',value:row=>row.metrics.playerOfMatch,render:row=>num(row.metrics.playerOfMatch,2)},
    {key:'ca',label:'C.A.',value:row=>row.metrics.ca,render:row=>num(row.metrics.ca)},{key:'pa',label:'C.P.',value:row=>row.metrics.pa,render:row=>num(row.metrics.pa)},{key:'rating',label:'Avaliação',value:row=>row.metrics.rating,render:row=>num(row.metrics.rating,2)},{key:'value',label:'Valor médio',value:row=>row.metrics.marketValue,render:row=>money(row.metrics.marketValue)},{key:'wage',label:'Salário médio',value:row=>row.metrics.wage,render:row=>money(row.metrics.wage)},{key:'clubRep',label:'Rep. clubes',value:row=>row.metrics.clubReputation,render:row=>num(row.metrics.clubReputation)},
    {key:'index',label:'Índice',value:row=>row.index,render:row=>num(row.index)},{key:'current',label:'Peso atual',value:row=>row.current,render:row=>num(row.current,2)},{key:'suggested',label:'Peso sugerido',value:row=>row.suggested,render:row=><strong>{num(row.suggested,2)}</strong>},{key:'diff',label:'Diferença',value:row=>row.difference,render:row=><span className={row.difference>=0?'market-positive':'market-negative'}>{row.difference>=0?'+':''}{num(row.difference,2)}</span>},
  ]
  const apply=()=>{const config=loadRankingConfig(),picked=rows.filter(row=>selected.has(row.id)),map=new Map(config.competitionSpecificWeights.map(item=>[item.match.toLowerCase(),item]));for(const row of picked)map.set(row.name.toLowerCase(),{match:row.name,label:row.name,weight:row.suggested});config.competitionSpecificWeights=[...map.values()];saveRankingConfig(config)}
  const exportJson=()=>{const content=JSON.stringify({version:2,formula,suggestions:rows},null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='recomendador-pesos.json';link.click();URL.revokeObjectURL(url)}
  const importJson=async(file:File)=>{const parsed=JSON.parse(await file.text()) as {formula?:Formula};if(parsed.formula)setFormula(parsed.formula)}
  const saveProfile=()=>{const name=formula.name.trim()||`Fórmula ${profiles.length+1}`,profile:FormulaProfile={id:`formula-${crypto.randomUUID()}`,name,formula:clone({...formula,name})},next=[...profiles,profile];saveProfiles(next);setProfiles(next);setActiveProfile(profile.id)}
  const deleteProfile=()=>{if(!activeProfile)return;const next=profiles.filter(row=>row.id!==activeProfile);saveProfiles(next);setProfiles(next);setActiveProfile('')}
  const activeCount=METRICS.filter(item=>formula.enabled[item.key]).length
  return <div className="page-stack">
    <Panel title="Recomendador de Pesos" description="Evolução da antiga Sugestão de Pesos: métricas configuráveis, normalização, perfis, comparação com os pesos atuais e aplicação seletiva.">
      <div className="form-grid"><label><span>Nome da fórmula</span><input value={formula.name} onChange={event=>setFormula(current=>({...current,name:event.target.value}))}/></label><label><span>Normalização</span><select value={formula.normalization} onChange={event=>setFormula(current=>({...current,normalization:event.target.value as Normalization}))}><option value="percentile">Percentis</option><option value="minmax">Mínimo–máximo</option></select></label><label><span>Escala máxima</span><input type="number" min={.1} step={.1} value={formula.scale} onChange={event=>setFormula(current=>({...current,scale:Number(event.target.value)}))}/></label><label><span>Perfil guardado</span><select value={activeProfile} onChange={event=>{setActiveProfile(event.target.value);const profile=profiles.find(row=>row.id===event.target.value);if(profile)setFormula(clone(profile.formula))}}><option value="">Nenhum</option>{profiles.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label></div>
      <div className="weight-formula-grid">{METRICS.map(item=><label key={item.key} title={item.description}><span><input type="checkbox" checked={formula.enabled[item.key]} onChange={event=>setFormula(current=>({...current,enabled:{...current.enabled,[item.key]:event.target.checked}}))}/> {item.label}</span><input type="number" min={0} step={.5} disabled={!formula.enabled[item.key]} value={formula.weights[item.key]} onChange={event=>setFormula(current=>({...current,weights:{...current.weights,[item.key]:Number(event.target.value)}}))}/><small>{item.description}</small></label>)}</div>
      <div className="ranking-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar competição…"/><select value={type} onChange={event=>setType(event.target.value)}><option value="all">Todos os tipos</option><option value="super-league">Super League</option><option value="national">Nacionais</option><option value="continental">Continentais</option><option value="international">Internacionais</option></select><button className="primary-button" disabled={!selected.size} onClick={apply}><Save size={15}/> Aplicar selecionadas</button><button className="secondary-button" onClick={saveProfile}><Copy size={15}/> Guardar perfil</button><button className="secondary-button" disabled={!activeProfile} onClick={deleteProfile}><Trash2 size={15}/> Apagar perfil</button><button className="secondary-button" onClick={()=>setFormula(clone(DEFAULT))}><RotateCcw size={15}/> Repor fórmula</button><button className="secondary-button" onClick={exportJson}><Download size={15}/> Exportar JSON</button><button className="secondary-button" onClick={()=>fileRef.current?.click()}><Upload size={15}/> Importar JSON</button><input hidden ref={fileRef} type="file" accept="application/json" onChange={event=>{const file=event.target.files?.[0];if(file)void importJson(file)}}/></div>
    </Panel>
    <div className="stats-grid"><StatCard label="Competições analisadas" value={rows.length}/><StatCard label="Selecionadas" value={selected.size}/><StatCard label="Métricas ativas" value={`${activeCount}/${METRICS.length}`}/><StatCard label="Peso médio sugerido" value={num(average(rows.map(row=>row.suggested)),2)} detail={`escala máxima ${formula.scale}`}/></div>
    <Panel title="Sugestões calculadas" description="Todas as colunas são ordenáveis e reorganizáveis. Cobertura baixa indica que a recomendação deve ser revista manualmente."><ReorderableScoreTable tableKey="weight-suggestions:v2" columns={columns} rows={rows} rowKey={row=>row.id}/></Panel>
    <Panel title="Metodologia" description="Como interpretar e aplicar a recomendação."><div className="profile-style-identity"><Lightbulb/><div><strong>Índice relativo à base importada</strong><p>Cada variável ativa é normalizada para 0–100, ponderada e renormalizada apenas com os dados disponíveis. A idade é invertida para representar juventude. O resultado é convertido para a escala escolhida e nunca substitui a decisão editorial sobre a importância de cada competição.</p></div></div></Panel>
  </div>
}
